### ISSUE TITLE
It is impossible to register cell types, renderers, editors and validators

### ISSUE THREAD

**Issue by baybal** [handsontable/vue-handsontable-official#104]
### Description

Handsontable vue should provide mechanism to register cell types, renderers, editors and validators.

As of now, it is impossible to do anything with the initial Handsontable object before it creates an instance.

**Comment by wojciechczerniak** [comment]
It does. Have you checked the docs?

https://handsontable.com/docs/6.2.2/frameworks-wrapper-for-vue-custom-renderer-example.html
https://handsontable.com/docs/6.2.2/frameworks-wrapper-for-vue-custom-editor-example.html

**Comment by baybal** [comment]
No,

Even if you do `Handsontable.cellTypes.registerCellType()` the `Handsontable` you have inside Vue, will not be able to pass the cell type to the constructor of the instance.

**Comment by wojciechczerniak** [comment]
Ok. Then I'll need more info to reproduce the issue:

```html
### Description
<!--- Tell us what happens and what should happen -->

### Steps to reproduce
<!--- Provide steps to reproduce this issue -->
1.
2.
3.

### Demo
<!--- Provide a link to a live example on JSFiddle or 
Codepen or fill the following demo with your settings -->
https://jsfiddle.net/handsoncode/4owqzasd/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:
```

**Comment by baybal** [comment]
I'll give you an example of code:

`import { HotTable } from '@handsontable/vue';
import { renderers, cellTypes } from 'handsontable';`

cellTypes.registerCellType(myCell);

let mycell =  {
		timeFormat: 'YYYY-MM-DD hh:mm:ss',
		renderer: timestampRenderer, // both timestampRenderer and TimestampEditor are working perfectly fine if used outside of  handsontable/vue
		editor: TimestampEditor,
}

**Comment by wojciechczerniak** [comment]
The example is incomplete, `timestampRenderer` and `TimestampEditor` are missing. Can't replicate the issue, sorry.

I will reopen when we have more info.
