### ISSUE TITLE
Settings objects watcher 

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/vue-handsontable-official#108]
### Description
Changing hotSettings attributes will result in an error: "Incorrect value of the columnsRenderCalculator" triggered by Vue watchers. Bug was tracked to:

https://github.com/handsontable/handsontable/blob/65dc03147e411df27e6c2699b93fdc7ade9bad67/src/core.js#L2905

That returns `undefined`, should have default value of `Infinity`. 

Then `Math.min(undefined)` returns `NaN` instead the correct value.

Somewhere in the Vue wrapper we change the default for `this.getSettings().maxCols`?

Support ticket no68

### Steps to reproduce
1. Try to update hotSettings object with vue-handsontable attribute

### Demo
Demo that was provided but was created with old wrapper version: 
https://codepen.io/morgenweck/pen/PVjMYx

Example updated to the latest vue-handsontable version and it doesn't work
https://codepen.io/anon/pen/BMPZxG

### Your environment
* Vue wrapper version: 3.1.0
* Handsontable version: 6.2.2
* Browser Name and version: Firefox, Chrome
* Operating System: OS X

**Comment by hugobyrne** [comment]
Is there a fix or workaround for this? 
Ive tried rolling back to version 2 in vue but it tells me I need this npm package which doesnt seem to exist
@types/handsontable__vue

**Comment by darian314** [comment]
Any update on when this is going to get fixed?

**Comment by AMBudnik** [comment]
Hey @darian314 we've attached the March milestone, it means that we're planning to fix it in March and publish in April (or faster we get get it done).

**Comment by wojciechczerniak** [comment]
@hugobyrne As a workaround it might work to use each option as a prop instead deeply nested settings object.

**Comment by morgenweck** [comment]
This is now May-- is it fixed?

**Comment by wojciechczerniak** [comment]
@morgenweck Not yet. Sorry, we were blocked longer then we expected. The bug is now resheduled to May and we're back on track to fix it.

**Comment by AMBudnik** [comment]
Hey @hugobyrne @darian314 @morgenweck 
we just got it fixed yesterday in v `4.1.0`.
