### ISSUE TITLE
Simplify JSFiddle used in new issue template

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/vue-handsontable-official#109]
### Description
We can simplify our JSFiddle demo for Vue

### Steps to reproduce

1. Current JSFiddle: https://jsfiddle.net/handsoncode/4owqzasd/
2. Unused prop `msg`, unnecessary nested in two `div` elements, unnecessary styles, have a non commercial license key (?)
3. New JSFiddle: https://jsfiddle.net/wrog94jm/

**Comment by jansiegel** [comment]
@wojciechczerniak, Is `width="600" height="300"` necessary? It creates an empty space between the table and the license information.

**Comment by wojciechczerniak** [comment]
@jansiegel Without width and height we will attach event to window. Basic use case for Handsontable should have defined size. Maybe we can use our helper to generate more data? And IMO we should enable row/colHeaders.

The point is to remove unncecessary `div` element, and `msg` prop, usa function to return `data` and add `non-commercial` license.
