### ISSUE TITLE
How can I get source for dropdown cell from api data?

### ISSUE THREAD

**Issue by ghost** [handsontable/vue-handsontable-official#114]
### Description

I would like to set source for dropdown cell which comes from get api data.

I'm trying to use handsontable of cell type, but it didn't solve the problem.

I guess this problem happened because of life cycle method of Vue/cli because table collapse when I use function to set column.

In this case, how do I manage contents of source?

### Your environment
* Vue wrapper version: 3.1.0
* Handsontable version: 6.2.2
* Browser Name and version: Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System: Windows 10 64bit

**Comment by AMBudnik** [comment]
Hey @astatsuya 

you can try to use the `cells` method. Here's a demo that shows how to get into the instance https://codepen.io/anon/pen/rZzXbg?editors=0010 from an external function. Then you just use the `updateSettings` method like here

```js
this.$refs.myTable.table.updateSettings({
          cells: function(){
            let cp = {};
            //settings new source array
            cp.source = newSource
            return cp
          }
      })
```

**Comment by tatsuya-asami** [comment]
> Hey @astatsuya
> 
> you can try to use the `cells` method. Here's a demo that shows how to get into the instance https://codepen.io/anon/pen/rZzXbg?editors=0010 from an external function. Then you just use the `updateSettings` method like here
> 
> ```js
> this.$refs.myTable.table.updateSettings({
>           cells: function(){
>             let cp = {};
>             //settings new source array
>             cp.source = newSource
>             return cp
>           }
>       })
> ```

Hi @AMBudnik 
Thank you for your reply and giving me an example!
I will try to do your way and update my condition.

**Comment by ghost** [comment]
> Hey @astatsuya
> 
> you can try to use the `cells` method. Here's a demo that shows how to get into the instance https://codepen.io/anon/pen/rZzXbg?editors=0010 from an external function. Then you just use the `updateSettings` method like here
> 
> ```js
> this.$refs.myTable.table.updateSettings({
>           cells: function(){
>             let cp = {};
>             //settings new source array
>             cp.source = newSource
>             return cp
>           }
>       })
> ```

Hi @AMBudnik
Thank you for your reply and giving me an example!
I will try to do your way and update my condition.

**Comment by ghost** [comment]
I solved my problem. Thank you so much!

```
     mounted: async function() {
        await this.getData();
        await this.cellProp();
    },
   
    cellProp: function() {
      const statusSources = this.test;

      this.$refs.hotTableComponent.hotInstance.updateSettings({
        cells: function(row, col, prop) {
          const cellProperties = {};
          if (col === -) {
            cellProperties.source = statusSources;
          }
          return cellProperties;
        }
      });
    }
```

**Comment by AMBudnik** [comment]
Great to hear that @astatsuya  :)
