### ISSUE TITLE
language not worked

### ISSUE THREAD

**Issue by lightning0016** [handsontable/vue-handsontable-official#117]
### Description

Handsontable.languages.getLanguagesDictionaries can found zh-Cn,but when set hot-table language="zh-CN"
console print error:
`Language with code "zh-CN" was not found. You should register particular language before using it`

### Steps to reproduce

1.use    import 'handsontable/languages/zh-CN';
2.set language='zh-CN'
3.i try other language the same happened,

### Demo

https://jsfiddle.net/handsoncode/4owqzasd/

### Your environment
* Vue wrapper version: 2.5.7
* Handsontable version:7.0 and vue 4.0
* Browser Name and version:chrome
* Operating System:win7

**Comment by AMBudnik** [comment]
Hey @lightning0016 

you should add the language pack script. I've added it here https://jsfiddle.net/4xh7n5ou/

**Comment by zhangwz** [comment]
> Hey @lightning0016
> 
> you should add the language pack script. I've added it here https://jsfiddle.net/4xh7n5ou/

but after I add language: 'zh-CN', set dropdownMenu:true，the table's dropdown menu is still English.

**Comment by AMBudnik** [comment]
Hey @zhangwz 

here's the language tutorial that can come in handy https://handsontable.com/docs/7.1.1/tutorial-internationalization.html and the language change example for Vue https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-language-change-example.html
