### ISSUE TITLE
Webpack instructions

### ISSUE THREAD

**Issue by zbyte64** [handsontable/vue-handsontable-official#12]
There should be instructions on how to make this work with webpack. The following worked for me:

```
module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: path.join(projectRoot, 'node_modules', 'vue-handsontable-official')
      },
      ...
   ]
}
```

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes this problem?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same bug in v2.0.0-beta1+
