### ISSUE TITLE
How to use placeholders?

### ISSUE THREAD

**Issue by bigtunacan** [handsontable/vue-handsontable-official#121]
### Description
Trying to add placeholders to cells in a row, but I'm only able to add the same placeholder text to every cell.

### Steps to reproduce
1. Add placeholder text as an array like: `placeholder: ['foo', 'bar', 'baz', 'etc']`
2. Expect placeholders to match up with columns

| col1 | col2 | col3 | col4 |
| foo  | bar   | baz  | etc   |

instead get

| col1                       | col2                       | col3                       |
| foo, bar, baz, etc | foo, bar, baz, etc, | foo, bar, baz, etc |

### Demo
```
		<script>
			Vue.component('hot-table', Handsontable.vue.HotTable );

			var product = new Vue({
					el: '#product',
					data: {
							settings: {
								data: [
								["2016", 10, 11, 12, 13, 6, 7],
								["2017", 20, 11, 14, 13, 6, 7],
							],
							placeholder: ['foo', 'bar'],
							colWidths: [100, 100, 250, 150, 100, 100, 100],
						}
					},
				});
		</script>
```

**Comment by AMBudnik** [comment]
Hey @bigtunacan 

`placeholder` can be only a string (not an array). Here's an example https://codepen.io/anon/pen/jjOaBx?editors=0010

**Comment by bigtunacan** [comment]
I would say then that this is a feature request.  I'm honestly not sure what value it is to have placeholder as a string. I believe it is much more useful to have an array of strings so different columns can have unique placeholders.  In the event someone wants the same placeholder for all columns this would still allow for that.

**Comment by wojciechczerniak** [comment]
You can use it as a `column` prop: https://codepen.io/anon/pen/NZPKEb?editors=0010

**Comment by bigtunacan** [comment]
@wojciechczerniak Thank you.
