### ISSUE TITLE
Vuex warning when commit mutation if data is array of objects

### ISSUE THREAD

**Issue by LucasMaes** [handsontable/vue-handsontable-official#123]
### Description
I'm creating a Vue component with the Vue Wrapper of HoT and making use of Vuex for handling the state (based on the example of https://handsontable.com/docs/7.0.0/frameworks-wrapper-for-vue-vuex-example.html). When I enable the strict mode on the vuex (https://vuex.vuejs.org/guide/strict.html) and my data is an array of objects (and not an array of arrays like in the example), I get the following Vuex warning:
[vuex] do not mutate vuex store state outside mutation handlers.

### Steps to reproduce

1. Set up an example like ttps://handsontable.com/docs/7.0.0/frameworks-wrapper-for-vue-vuex-example.html
2. Create a data object which is an array of objects
3. Make sure that Vuex is in strict mode
4. Open console window of browser
5. Modify the content of the cells to commit a mutation
6. Notice the warning in the console log

### Demo

The first 3 steps are already setup in this jsfiddle:
https://jsfiddle.net/x4ngL6rp/4/

### Your environment
* Vue wrapper version: 4.0.0
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 75
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
You're right.

Once we turn on the `strict` mode we get the error https://jsfiddle.net/handsoncode/g24ztrjw/

I will leave it for investigation.

**Comment by wojciechczerniak** [comment]
`this.$store.commit('updateData', this.hotRef.getSourceData());` commits to Vuex reference to inner Handsontable `data` property. So each time Handsontable tries to modify data internally the change is propagated to Vuex storage through reference.

You need to break the reference between those objects ie. by creating a deep copy.

**Comment by LucasMaes** [comment]
Gotcha.

So it is basically a trade-off between the traceability of the mutations vs the performance hit of the deep copy.
