### ISSUE TITLE
How to perform a CURD operation?

### ISSUE THREAD

**Issue by rddewan** [handsontable/vue-handsontable-official#124]
### Description
How to perform a CURD operation ?  I am using laravel 5.8

### Your environment
* Vue wrapper version:
* Handsontable version: 7.1.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @rddewan 

What operations did not work for you?

Here's an example with Vue and Handsontable https://jsfiddle.net/AMBudnik/qpLyhwo1/

**Comment by rddewan** [comment]
Hi @AMBudnik  
How can i perform a CURD operation through inline cell editing ?

**Comment by AMBudnik** [comment]
Can you share more details about the requirements?
I've found a couple of scenarios for inline editing.

**Comment by rddewan** [comment]
I am fetching the data from MySql Database and displaying it using handsontable in laravel vue . I would live to preform CURD operation directly using cell editing .

**Comment by AMBudnik** [comment]
Handsontable by default is editable for all the cells by a dbclick and <kbd>ENTER</kbd> click. At the same time, it can only have one active opened editor.
If you wish to enable editing for a single row you'd need to create custom logic. If you need more help with that task I please share all the project requirements with me on support@handsontable.com

**Comment by rddewan** [comment]
thanks after double clicking and update the cell value  how do i call the update method in vue
methods: {
     updateRecord() {
         axios.post (......)
     }
}

**Comment by AMBudnik** [comment]
Saving data to the server can be made via AJAX call https://handsontable.com/docs/7.1.0/tutorial-load-and-save.html in the `afterChange` hook.

![Zrzut ekranu 2019-07-15 o 12 46 06](https://user-images.githubusercontent.com/10757813/61210981-87b1ef00-a6fe-11e9-9bf3-1d3db7db4ecf.png)

**Comment by rddewan** [comment]
thank you  i will check it out
