### ISSUE TITLE
Undo no longer works after setting backwards reactivity to data

### ISSUE THREAD

**Issue by waltermaldonado** [handsontable/vue-handsontable-official#130]
Since I need to add reactivity to the table data array, I had to implement the afterChange method as below:
```
afterChange: (changes) => {
     changes.forEach(([row, prop, oldValue, newValue]) => {
        Vue.set(this.data[row], prop, newValue);
    });
},
```

And now my undo function no longer works. If I comment out the `Vue.set()` line it works normally, but I lose the reactivity to the table data when it changes.

I tried the workarounds discussed in #20 but had no success at all.

**Comment by wojciechczerniak** [comment]
We will need more details:

```
### Description
<!--- Tell us what happens and what should happen -->

### Steps to reproduce
<!--- Provide steps to reproduce this issue -->
1.
2.
3.

### Demo
<!--- Provide a link to a live example on JSFiddle or Codepen 
or fill the following demo with your settings -->
https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:
```

**Comment by waltermaldonado** [comment]
### Description
The undo (Ctrl+Z) should work after changing the content of cell but it does not.

### Steps to reproduce
Add this code to the afterChange() hook:
```
afterChange: (changes) => {
     changes.forEach(([row, prop, oldValue, newValue]) => {
        Vue.set(this.data[row], prop, newValue);
    });
},
```
and try to undo after changing a cell.
### Demo
https://jsfiddle.net/of53c0L4/6/

### Your environment
* Vue version: ^2.6.10
* Vue wrapper version: ^4.0.0
* Handsontable version: ^7.1.0
* Browser Name and version: Chrome 76.0.3809.87 64-bits
* Operating System: Ubuntu 18.04.2 LTS (Linux 4.18.0-25-generic)

**Comment by wojciechczerniak** [comment]
Now I see. You're changing `this.data`, which will then reload data in Handsontable. This will create new undo stack because Handsontable was reloaded.

You shouldn't modify Handsontable internal data storage by reference. Clone the data and store it somewhere else.

**Comment by waltermaldonado** [comment]
I don't know if I followed, but if you change the variable `data` to any other name the problem persists (See fiddle again). Also, if I do so how would I get reactivity from the table when some cell is changed?

**Comment by wojciechczerniak** [comment]
Child components can't change props. If you need to pass an array or an object to a child component then you have to be very careful. Or create a copy. You get changes through events., in Handsontable called `hooks` and used as callbacks. Use our hooks to listen for changes and then update your state / variable.

**Comment by waltermaldonado** [comment]
Fine. I tried to do that: created a `dataCopy` variable and then updated this variable upon changes in the table. The data is reactive, as expected, but the undo function does not work. It looks like calling `Vue.set()` in the hook triggers reloading in the table data, as you said, even in another variable. 

See fiddle: https://jsfiddle.net/nbuxsg78/2/

**Comment by wojciechczerniak** [comment]
First `afterChange` event is called `afterLoadData` without changes. In your code this throws an error and affects undo. Try this: https://jsfiddle.net/c4f18tow/1/

**Comment by waltermaldonado** [comment]
Perfect! Thank you very much!
