### ISSUE TITLE
How to set TD className by using hotColumn?

### ISSUE THREAD

**Issue by chao** [handsontable/vue-handsontable-official#132]
I tried to set TD classname by passing a class-name property from hot-column component.
But it doesn't work.

```JavaScript
<hot-table :settings="hotSettings">
  <hot-column :width="250" class-name="hot-custom">
    <custom-renderer hot-renderer></custom-renderer>
  </hot-column>
</hot-table>
```

How can I set my custom-renderer cell TD classname?

**Comment by wojciechczerniak** [comment]
With `cells` callback you can set `props.className` string: https://handsontable.com/docs/7.1.1/Options.html#cells

Those might work:
```vue
<custom-renderer hot-renderer :class="custom-class" :style="{ background-color: '#000' }"></custom-renderer>
```

But I'm not sure, there were no such feature request yet. This works for `<hot-table>` element: https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-custom-id-class-style.html

**Comment by chao** [comment]
Thanks for prompt response, I tried both `cells` function and set class property on `hot-renderer` way, but none of them works.

I also tried to change the TD class in my custom renderer.

<img width="509" alt="Screen Shot 2019-08-17 at 10 57 25 AM" src="https://user-images.githubusercontent.com/55872/63205896-e8f22700-c0dd-11e9-9ca2-2aef97abc8b0.png">

The class name only exists for about one second then it was replaced. I'm not sure what happens.

![Untitled](https://user-images.githubusercontent.com/55872/63205939-89484b80-c0de-11e9-8a51-fd79c37f6d59.gif)

**Comment by AMBudnik** [comment]
Hey @chao 

Can you place the code in the [CodePen](https://codepen.io/anon/pen/QVKBLZ?editors=1010) or [JSFiddle](https://jsfiddle.net/handsoncode/g24ztrjw/). I'd like to test it.

**Comment by chao** [comment]
Here is the example code in the [JSFiddle](https://jsfiddle.net/czhou/tv3opcg7/18/), the code regenerate the data in hot table in every 5 seconds. When the hot renderer components was rendered at the first time the class name was added to TD element and the background color is set to yellow. However when the data updated in 5 secs later, that class name on TD element was removed.

**Comment by AMBudnik** [comment]
Thank you for sharing the demo.
As this is a new data all the metadata is gone. You'd need to attach the `className` once again.

**Comment by chao** [comment]
How can I re-attach the className when value changed? I add a watcher to `value` property to change className but it doesn't work.

[Example](https://jsfiddle.net/czhou/tv3opcg7/21/)

**Comment by AMBudnik** [comment]
Hey @chao 

Here's the working example https://jsfiddle.net/gu752nsv/
It needed a bit of additional logic to get the instance reference.

**Comment by chao** [comment]
@AMBudnik 
You only changed the DIV class inside TD. I'm sure you can do that. The problem is we need to set the whole TD class.

**Comment by AMBudnik** [comment]
Hey @chao 

here's https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-hot-column.html a tutorial on how to use the renderer for hot-column It should clarify doubts

**Comment by chao** [comment]
Thanks for the document, I have read that part many times but I cannot get a solution. An example would be great.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting. I was waiting for a developer's feedback. Here's the updated example https://jsfiddle.net/2j9notux/

**Comment by chao** [comment]
Thanks for the answer, so that we still have to use hot table renderer function to set TD classname. I hope hot-column will support such function in the future.

**Comment by jasonlfunk** [comment]
I'm encountering this issue too. And @AMBudnik's latest solution isn't an option as the `cells` callback doesn't seem to be used for custom-renderers. 

Here is what should work, but doesn't: https://jsfiddle.net/jrhkb5Lm/2/
A you can see, the class-name property is correctly applied to TDs in column B but not in column A.

I noticed in the documentation that custom renderers should extend one of the built in renderers but I don't see how that's possible with a vue component. 

I'd love to know how to make this work.

**Comment by wojciechczerniak** [comment]
@jasonlfunk  Extending TextRenderer is just a shortcut. You can have the very same login in your own custom-renderer. Take a look at https://github.com/handsontable/handsontable/blob/master/src/renderers/_cellDecorator.js what we're doing internally. Import `cellDecorator` from `handsontable/es/renderers/_cellDecorator.js` and apply it in the first line of your renderer or copy the code to your app.

**Comment by jasonlfunk** [comment]
@wojciechczerniak Thanks. That has gotten me a bit closer.

See this updated fiddle: https://jsfiddle.net/6t9bmzn8/3/

Everything looks fine on the first load. But if you made any changes to column A, the classes get reset. I tried adding a watcher to the `value`, which fixed it for the column you change. But it still clears the rest of the cells in the column. I presume because the value doesn't change, so the handler is not called.

On a side note, why are those cells getting re-rendered when their value isn't changed? It seems like there might be room for performance improvements there.
