### ISSUE TITLE
When setting columns I want to set the data part of the col to be a getter func.

### ISSUE THREAD

**Issue by vix515** [handsontable/vue-handsontable-official#133]
Loading an array of objects 'Loans' as table-data and then

When setting up columns:

```
  {
          data: getPropertyName,
          editor: false,
        }
```

```
class Loans {
  public PropertyName = 1111111

  constructor(property:Property,) {
    this.propertyName = property.name
  }

  get getPropertyName():String {
    return 'Big House'
  }
}
```

When putting the function name as the column-data parameter nothing is displayed. But if I put the variable name 'PropertyName' it works. I want to use getter functions to display the col-data.

**Comment by AMBudnik** [comment]
Have you tried to use the function in `columns` instead of an array of objects?

**Comment by vix515** [comment]
> Have you tried to use the function in `columns` instead of an array of objects?

Sorry yeah, I pass the data and in columns I set the getter function to get the data. 

 ```
get columns() {
    const cols: any = []
    this.activeColumns.forEach((x) => {
        cols.push({
          data: x.getter, //getter function passed here
        })
    });
    return cols;
  }
```

**Comment by AMBudnik** [comment]
Does it work smoothly in your case @vix515 ?
