### ISSUE TITLE
How to add customized hook callback

### ISSUE THREAD

**Issue by Guobacai** [handsontable/vue-handsontable-official#134]
### Description
We had a customized "select row" plugin in the handsontable. Every time a row is selected, it runs the hook "afterSelectedRowsChanged". We need to add a local callback to hotInstance. Is there any recommended way to do?
I have tried to do the following in "mounted", but failed.
`
this.$refs.table.hotInstance.addHook('afterSelectedRowsChanged', () => {});
`

### Your environment
* Vue wrapper version: 3.0.0
* Handsontable version: 3.0.0
* Browser Name and version: 
* Operating System:

**Comment by AMBudnik** [comment]
Hey @Guobacai 

if you need a hook that runs after changes you can use the `beforeChange` and `afterChange` in the combination of `getSelectedLast` method. Have you already tried it?

**Comment by Guobacai** [comment]
Hi @AMBudnik 

Thanks for your quick response. I did try "afterChange" and "afterInit". The "hotInstance" is null in both cases.
```
<EntityTable>
  <Table>
    <HotTable></HotTable>
  </Table>
</EntityTable>
```
In the "EntityTable", I passed the handler of "afterInit" to the HotTable. But, inside of the handler, I couldn't get the hotInstance.

**Comment by AMBudnik** [comment]
[Here's an example that can help](https://codepen.io/anon/pen/QVKBLZ?editors=1010). It's designed to export files, but it uses the hot instance in a reference - exactly what you need right now. 
You need to add the `ref="name"` tag in the `<hot-table>` element. And then by using the reference you get to the instance `this.$refs.name.table`.

**Comment by Guobacai** [comment]
Hi @AMBudnik 
Thanks so much for the answer. I think my question wasn't very clear.
What I want to know is if I want to add a **customized hook callback** to an instance of Handsontable Vue, at which lifecycle should I call the following function? "mounted" or "updated"?
`this.$refs.table.hotInstance.addHook('afterSelectedRowsChanged', () => {});`
Or, is there any other recommended way to add a **customized hook callback**?

**Comment by AMBudnik** [comment]
[Here, in the Vuex example](https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-vuex-example.html), we use an update callback (called each time the data changes) directly in settings. You do not need to refer to Vue's lifecycle hooks. 
`Mounted` is used is cases like here https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-language-change-example.html when we want to load a language and then use the table.
