### ISSUE TITLE
Why  the cellProperties  properties rolled back in hot-column component

### ISSUE THREAD

**Issue by chen-ABC** [handsontable/vue-handsontable-official#136]
### Description
I wanted to render different components based on cellMeta custom properties, but I found that clicking on other area after setting the properties,  properties   would roll back 
What should I do?

### Demo
https://jsfiddle.net/1h0dbqL8/1/

### Your environment
* Vue wrapper version: 4.1.0
* Handsontable version: 7.1.1
* Browser Name and version: chrome 59
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hey @chen-ABC 

`cells` is called on every `render()`. You may add a condition to block it if the `name` is already defined as `new`. (it depends on the project requirements).

**Comment by chen-ABC** [comment]
a method:
I stored cellsMeta  on  the vuex.

custom-render:
![image](https://user-images.githubusercontent.com/30097790/66905142-e194be80-f037-11e9-96cb-63afbe9e7dbd.png)

Like the official example : https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-vue-hot-column.html#v-model

**Comment by AMBudnik** [comment]
That is totally fine and it should be done this way but once you use `cells` method and attach new values for the same properties they are attached after each render of the table as they have higher priority.
