### ISSUE TITLE
Breaks Vue devtools in Chrome and Firefox

### ISSUE THREAD

**Issue by rwspielman** [handsontable/vue-handsontable-official#140]
### Description
I want to inspect a component that has a handsontable in it. when i go to inspect it, I get the following error:

`TypeError: can't convert symbol to string`

### Steps to reproduce

1. Install @handsontable/vue , build a component with a simple table on it
2. install vue devtools in either google chrome or firefox
3. open vue devtools, in the "components" tab, go to the parent component that has the handsontable on it, observe console logs and observe that 

### Demo

Not sure this will be helpful as you can't use the vue devtools on jsfiddle or codepen

### Your environment
* Vue wrapper version: 2.5.17
* Handsontable version: 7.2.2
* Browser Name and version: Google Chrome Version 77.0.3865.120 (Official Build) (32-bit), Firefox 69.0
* Operating System: Windows

**Comment by AMBudnik** [comment]
Welcome @rwspielman 

to solve this issue we need to wait for VueJS to merge this pull request https://github.com/vuejs/vue/pull/10529

Topic explained here https://forum.handsontable.com/t/after-set-ref-attribute-in-table-shows-error/3738/1
Update [topic](https://forum.handsontable.com/t/typeerror-cannot-convert-a-symbol-value-to-a-string/3768) after fixing

**Comment by aeshakhzod** [comment]
Still facing this issue

**Comment by AMBudnik** [comment]
Thank you for noticing @shakhzodkudratov . The fix https://github.com/vuejs/vue/pull/10529/files#diff-3b87ec2a3813f1641aecdefdf4df80d20e1dc1078e05f17e1bc312aadc4f0127L219 is already on their `dev` branch. It means that soon we will be able to do the work on our side.

**Comment by AMBudnik** [comment]
This issue should no longer be replicable using the latest Handsontable for Vue  and Vue [2.6.11+](https://github.com/vuejs/vue/releases/tag/v2.6.11)

@rwspielman @shakhzodkudratov please confirm if it also works for you.
