### ISSUE TITLE
vue watch CustomRenderer  cellProperties  error

### ISSUE THREAD

**Issue by chen-ABC** [handsontable/vue-handsontable-official#141]
### Description
I need to listen for cellProperties changes for the next step
but an error occurred
![image](https://user-images.githubusercontent.com/30097790/67541393-5db79200-f71b-11e9-80c8-36a0e5831b3d.png)

watch code
```
cellProperties:{
    deep:true,
    handler(value){
    	console.log(value.name)
    }
    }
```

### Demo

https://jsfiddle.net/26cwr3zv/4/

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.1.1
* Browser Name and version: chrome 64
* Operating System: window 10

**Comment by AMBudnik** [comment]
Thank you for investigating this subject @chen-ABC 

It looks like we get the same calls over and over again. As soon as we remove `Deep` the process stops.

However, with the number of hooks that Handsontable brings you should be able to get the same amount of information. If you won't be able to find it in the docs I'll be happy to help.

**Comment by AMBudnik** [comment]
Nevertheless, we should describe this situation in the docs or a blog post as many tutorials (including VueJS documentation) mention `deep` as a proper way to watch changes in the application.

**Comment by chen-ABC** [comment]
@AMBudnik thanks, I've learned

**Comment by chen-ABC** [comment]
@AMBudnik thanks, I've learned

**Comment by chen-ABC** [comment]
@AMBudnik thanks, I've learned

**Comment by chen-ABC** [comment]
@AMBudnik thanks, I've learned
