### ISSUE TITLE
Copy and Past and Data Entry is generating -> [Object Object] 

### ISSUE THREAD

**Issue by waynermaia** [handsontable/vue-handsontable-official#143]
### Description
Well, when copy data from data table since be a type collapsible and paste in excel or other spreadsheet based table is showing [Object Object] into cells.
  
 
### Steps to reproduce

1. Create a Collapse table with Handsontable 
2. Copy some data of any cell
3. Paste into cell on excel

### p.s
Data entry also is showing [Object Object].

### Demo

http://jsfiddle.net/gr47deqa/1/

### Your environment
* Vue wrapper version: 4.0.0
* Handsontable version: 7.1.0
* Browser Name and version: Chrome Versão 78.0.3904.70 (Versão oficial) 64 bits
* Operating System: macOS Mojave and Windons 10

**Comment by wojciechczerniak** [comment]
Correct. You keep an object as value and when it's stringified for the clipboard the result should be `[Object Object]`. You can use `beforeCopy` hook to map the values to simpler values before Handsontable stringifies the data.
