### ISSUE TITLE
Manually merged cells become unmerged after addded  new rows

### ISSUE THREAD

**Issue by webwhy** [handsontable/vue-handsontable-official#144]
### Description

now: Manually merged cells become unmerged after addded  new rows
hope: dont be
### Steps to reproduce

1.first merge some cells
2.then insert a row anywhere
3.those merged cells become unmerged

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
I'm closing this issue as this is the same one as https://github.com/handsontable/handsontable/issues/6434

ps. Please go to https://github.com/handsontable/handsontable/issues/6434 and attach a demo where the issue can be replicable
