### ISSUE TITLE
the bind data is not sorted when the column sort.

### ISSUE THREAD

**Issue by leavesgreen** [handsontable/vue-handsontable-official#146]
### Description
I make a table by use the option    columnSorting: true,  in order to sort the table data. 
when I click the column head. the data in the table do re-ordered. but when i change one of the cell. I want to get the row index to change another cell by the afterChange callback. and I do got the row index. but when I use the index to get the data row of the table data which the table binded(not in the grid). it is still in the past order . so I got a wrong data row.

### Steps to reproduce

1.set a able by a data.
2.sort the table by one column.
3.try to update another cell of the modified cell row. get the row index, and get the data in step 1 by index. 

I also try to use the method getDataAtRow method. but when use vue I can't get the variable called hot1 or whatever...

so many thanks.

**Comment by AMBudnik** [comment]
Hey @leavesgreen 

Please let me know what exact steps should I take while using this demo https://jsfiddle.net/AMBudnik/qo4jr0d6/? That's `7.3.0` of Handsontable with the Vue wrapper.

**Comment by leavesgreen** [comment]
@AMBudnik , thank you so much.
Sorry that  I can't open the link of jsfiddle.net ; it looks like I was blocked by my domain corp.

Let me explain the question in this steps. may be it's clear a little bit.

I use the Vue like follow:

`  new Vue({
    el: '#example1',
    data: function() {
      return {
        hotSettings: {
          data: [['A',1,10],['B',2,20],['C',3,30]],
          colHeaders: true,
          columnSorting: true,
          colHeaders:['Col1','Col2','Col3']
        }
      }
    },
    components: {
      HotTable
    }
  });
`
` <hot-table :settings="hotSettings" colHeaders="true" rowHeaders="true"></hot-table>`

1)  first it works fine. when I change the number 10 of row first to 1.2 , the data is also synced as 1.2
2) Then I want to change A to A1.2 when the number 10 changed. so I add the follow callback function in the hotsetting :
`               afterChange: (changes) => {
                  if(changes){
                    changes.forEach(([row, prop, oldValue, newValue]) => {
                        let row1= this.hotSettings.data[row];
                        row1[0] = row1[0]+newValue.toString();
                        this.$set(this.hotSettings.data,row, row1);
                    });
                  }
                }`
It also works fine. the I changed the data here, so the cell of the table also updated by automatically.
3)then I use the column sort. I click the Col3 then sort by desc, so the number 30 is first row now. 
then I change the number 10 to 1.2 --now it the last row.
the problem now come out. the callback function got the current row is 2(the last row), so I get the third row of the data object. but the data is not sort by desc. as they showed in the table. so I got the  row ['C',3,30], and change the C to C1.2
 
now it not the correct result. 
so all my question is , how can I got the row of number 10--the  first row and now the last row, by the row index =2 ?

**Comment by AMBudnik** [comment]
Hey @leavesgreen 

to change the data in the `afterChange` I recommend using[ `setDataAtCell` method](https://handsontable.com/docs/7.3.0/Core.html#setDataAtCell). 
You should remember to add the last parameter (your custom string)

![image](https://user-images.githubusercontent.com/10757813/70908718-317a0c80-200c-11ea-86cb-36ee8c1baf47.png)

In other way you'd end up with an infinite loop and a hanged browser.

**Comment by leavesgreen** [comment]
thank you. @AMBudnik 
this is another question, when I use Vue, I have not a variable like hot1, and I dont't know how to get it.
so I tried use this.setDataAtCell in the afterChange callback method directly, and certainly it is undefined.

**Comment by leavesgreen** [comment]
thanks a lot @AMBudnik ;
I found a way to get the ref to hot1 instance. by the Vue ref attr,
`this.$refs.hot1.hotInstance`
maybe it's not the best way . but it really work fine.
thank you again. your grace.

**Comment by wojciechczerniak** [comment]
Hi @leavesgreen It is the best and recommended way: https://handsontable.com/docs/7.3.0/frameworks-wrapper-for-vue-hot-reference.html
