### ISSUE TITLE
nestedHeaders是否能够实现行的合并

### ISSUE THREAD

**Issue by ZwjDreamMail** [handsontable/vue-handsontable-official#149]
### Description
目前nestedHeaders多表头可以实现多列合并成一列，但是不支持多行合并成一行

**Comment by AMBudnik** [comment]
Hey @ZwjDreamMail 

The Handsontable itself does not support `rowspan` of columns yet. This topic is mentioned here https://github.com/handsontable/handsontable/issues/6553
