### ISSUE TITLE
text renderer function in vue handsontable official package 

### ISSUE THREAD

**Issue by npaulOB** [handsontable/vue-handsontable-official#15]
How can I use textRenderer or imgRenderer function in vue handsontable package? I am validating a CSV file and I need to highlight the error cells / td.

**Comment by sonmunehiro** [comment]
+1

**Comment by ccccps** [comment]
Add `import Handsontable from 'handsontable'`,
and use like `Handsontable.renderers.TextRenderer`

**Comment by mrpiotr-dev** [comment]
Hi @npaulOB,
Here is an example: https://codepen.io/swistach/pen/LmBGpP
