### ISSUE TITLE
Update to support v8.0.0

### ISSUE THREAD

**Issue by aninde** [handsontable/vue-handsontable-official#165]
### Description
We should update the Vue-Handsontable to support v8.0.0 

### Your environment
* Vue wrapper version:
* Handsontable version: 8.0.0 v. 
* Browser Name and version: all supported
* Operating System: n/a

**Comment by Guobacai** [comment]
The Handsontable beta2 just comes out. Looks like the `Handsontable.DefaultSettings()` is no longer a constrcutor.
This works on beta1 though.

You can see the error in this fiddle:
https://jsfiddle.net/guobacai/9dhp3tn7/13/

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @Guobacai 
We will test it once we prepare Vue to use 8.0.0.-beta2.

**Comment by AMBudnik** [comment]
Hi @Guobacai we just released Handsontable for Vue https://github.com/handsontable/vue-handsontable-official/releases/tag/5.0.1. I hope that it solves your issue, but if not feel free to create a new topic or send me an email support@handsontable.com
