### ISSUE TITLE
change class using cellProperties 

### ISSUE THREAD

**Issue by noninyo** [handsontable/vue-handsontable-official#166]
### Description
I would like to change the background of a cell base on his value.
I change cellProperties.className in cells function but this doesn't help.
any I idea how can I do it?
Thanks! 

### Demo

https://jsfiddle.net/noninyo/jv6t82gh/17/

**Comment by AMBudnik** [comment]
Hey @noninyo 

here's an article full of cell dependencies example https://handsontable.com/blog/articles/2016/4/expand-your-app-with-cell-dependencies I guess that the [first one](https://jsfiddle.net/handsoncode/usfko0gL/?utm_source=website&utm_medium=embed&utm_campaign=usfko0gL) fit your project well.

In this example, we use the `beforeChange` hook to check the new value of a cell and attach `className` (this is where you can set your background).

**Comment by noninyo** [comment]
Hi,

Thanks for the answer!
I try using both beforeChange and afterInit but got no change
you can see it here 
https://jsfiddle.net/noninyo/jv6t82gh/31/

**Comment by AMBudnik** [comment]
Here's an updated demo https://jsfiddle.net/w72onxkm/

I just removed

![image](https://user-images.githubusercontent.com/10757813/73654382-d4095000-468b-11ea-9e59-154eab34525a.png)

JSFiddle have its own handling of containers and it opens the `style` in the invisible area.

**Comment by noninyo** [comment]
Thanks for the help!
It work now :)
