### ISSUE TITLE
Pasting in > 1000 rows of data causes validation errors due to max ajax requests

### ISSUE THREAD

**Issue by rwspielman** [handsontable/vue-handsontable-official#167]
### Description

Pasting in lots of data with an ajax validation causes an overload of requests on google chrome. it prevents the data from being pasted and showing up in the table

### Steps to reproduce

1. Add validation to a column and have it send an ajax requests
2. Paste in 2000 values from excel
3. Observe in the network tab that XHR requests begin to fail towards the end
4. Fail to load resource: net::ERR_INSUFFICIENT_RESOURCES is an error in the console. 

### Demo

https://jsfiddle.net/khwsgdc3/

copy/paste 1-2000 in there 

### Your environment
* Vue wrapper version: 2.5.17
* Handsontable version: 4.1.1
* Browser Name and version: Google Chrome Version 79.0.3945.130 (Official Build) (32-bit)
* Operating System: Windows 10

Is there a way to implement a queue to prevent the max # of requests being hit

**Comment by rwspielman** [comment]
added axios-rate-limit as a package to throttle it, but is there any way to calculate them column-wise in a batch?

**Comment by AMBudnik** [comment]
Hey @rwspielman 

can you send over a demo? When I copy `2` column x `2000` row array into you `A1` cell I get this

![image](https://user-images.githubusercontent.com/10757813/73827713-56b31c00-4800-11ea-9ccc-18e3300ef1b8.png)

**Comment by rwspielman** [comment]
I receive the following image as well.
It seems to hit a 1000 requests limit because there is no rate limit throttling. In the network tab, it says failed on the request.

<img width="1059" alt="2020-02-05 09_25_30-Edit fiddle - JSFiddle" src="https://user-images.githubusercontent.com/20442310/73855405-a93d0a00-47f9-11ea-9748-c8c22e64743b.png">

<img width="488" alt="2020-02-05 09_28_16-Edit fiddle - JSFiddle" src="https://user-images.githubusercontent.com/20442310/73855581-e1444d00-47f9-11ea-83d1-ca35b1330f8c.png">
