### ISSUE TITLE
Module not found: Error: Can't resolve 'handsontable'

### ISSUE THREAD

**Issue by codingstuff91** [handsontable/vue-handsontable-official#168]
### Description
I use VUE-CLI and i tried to test HOT for a new project.

I tried to create a sample test table in the about view that the vue cli generates for me.

Though I refer to the example that i found on the official documentation see below : 

> <template>
>   <hot-table :data="data" rowHeaders="true" colHeaders="true"></hot-table>
> </template>
> 
> <script>
>   import { HotTable } from '@handsontable/vue';
> 
>   export default {
>     data: function() {
>       return {
>         data: [
>           ["", "Ford", "Volvo", "Toyota", "Honda"],
>           ["2016", 10, 11, 12, 13],
>           ["2017", 20, 11, 14, 13],
>           ["2018", 30, 15, 12, 13]
>         ],
>       };
>     },
>     components: {
>       HotTable
>     }
>   }
> </script>

but when webpack do the compilation it displays the message below : 

> Failed to compile.
> 
> ./node_modules/@handsontable/vue/es/vue-handsontable.js
> Module not found: Error: Can't resolve 'handsontable' in 'C:\laragon\www\table_spreadsheet\node_modules\@handsontable\vue\es'

Maybe i did something wrong and i dont know what...

### Steps to reproduce

1. Use VUE-CLI
2. Install the depedency HANDSONTABLE latest version 4.1.1
3. launch the SERVE function

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.3.0
* Browser Name and version: Chrome Version 79.0.3945.130 (Build officiel) (64 bits)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
hey @codingstuff91 

would you be able to send the project .zip to support@handsontable.com?

**Comment by codingstuff91** [comment]
Hi,
Sorry to answer so late. 
I found myself my problem.

It was because i didnt import the Handsontable plugin before using it with the vue specific one.

**Comment by pnowak** [comment]
Hi @codingstuff91 

Thanks for the information.
So I close the issue.
