### ISSUE TITLE
LicenseKey

### ISSUE THREAD

**Issue by brianvoe** [handsontable/vue-handsontable-official#17]
I added license key to the setting being passed in and it still doesnt get rid of the trial div and i still get a console log error.

**Comment by AMBudnik** [comment]
Hi @brianvoe 

Please contact me at support@handsontable.com. I will check if the key is valid.

**Comment by AMBudnik** [comment]
The conversation has been continued on emails.

For all users who have similar problems: please use the above email channel to contact me directly.
