### ISSUE TITLE
Watch Cell Changes  before after values  ?

### ISSUE THREAD

**Issue by gelinger777** [handsontable/vue-handsontable-official#171]
Sorry for a very newbie question. But I want to achieve following in the Vue version and couldn't figure it out. 

My component   is set as  following. 

   ```      <hot-table  :settings="hotSettings" :data="workbook"  colHeaders="" rowHeaders="" width="1400" height="1000"></hot-table>```

I am dynamically changing the whole data object. I want on each cell value change fire an event and be able to compare value before with value now and if change is negative color background with red or green if vice versa. 

Currently I have a custom renderer , which apparently has no idea what was the value Before 

```
import { HotTable } from '@handsontable/vue';
 import Handsontable from 'handsontable';




Handsontable.renderers.registerRenderer('custom-renderer', function(hotInstance, td, row, column, prop, value, cellProperties) {
 
 ///console.log(value);
 

  cellProperties.placeholder = value;
Handsontable.renderers.TextRenderer.apply(this, arguments);
  td.style.fontWeight = 'bold';
  td.style.color = 'white';
  td.style.background = '#152126';
})

```  
Any idea how to achive this in Vue version? 

Also is it possible in Vue version to pass the map of styling data?

**Comment by pnowak** [comment]
Hi @gelinger777 

I think you could use a state manager to keep data. After each change, you could compare the previous data with the new one.
Here is an example with Vuex - https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-vue-vuex-example.html

What do you mean by `pass the map of styling data`? 

Last but not least, can you show your implementation? It could be much easier to find a solution.

**Comment by gelinger777** [comment]
@pnowak  thank you for your answer. I didn't thought about the Vuex. I will give a try. 

styling thing I have solved already . Only thing is left how to animate background with like short blink . Maybe already Vue Handsontable or Handsontable already have something like that .. ??

**Comment by pnowak** [comment]
No, we don't use `blinking` background. 
But you could easily achieve this by CSS, e.g. - http://jsfiddle.net/umz8t/6490/
