### ISSUE TITLE
Passing props to the renderer components.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/vue-handsontable-official#172]
### Description
It looks like currently it is impossible to pass props to the renderer components.

### Steps to reproduce
1. Go to http://jsfiddle.net/js_ziggle/1jy4o0Lf/
2. The `test-prop` prop should be readable in the renderer component, but it's not.

### Demo
http://jsfiddle.net/js_ziggle/1jy4o0Lf/

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.4.2

**Comment by magikadev** [comment]
Same question here.

**Comment by magikadev** [comment]
It's working. Thanks @jansiegel

**Comment by magic990619** [comment]
Thank you for your work, @jansiegel 
Well, I am working on an educational projects and I have to use handsontable.
Is there any way to use your commit at the moment?
Till release new version, it's quite long time for me. 
Thanks.

**Comment by magikadev** [comment]
How can I use it on my website before release fixed version?

**Comment by pnowak** [comment]
I responded to your comment here - https://github.com/handsontable/vue-handsontable-official/issues/177#issuecomment-643201997

**Comment by magikadev** [comment]
Hi, @pnowak , @jansiegel , @jasonlfunk

Passing props is working well on codesandbox.
https://codesandbox.io/s/clever-bardeen-jvt00
But it's not working on my project. I cloned the develop branch, build it and use it on my project.
Attached is the one that I built and use in the project. (/node_modules/@handsontable)
[@handsontable.zip](https://github.com/handsontable/vue-handsontable-official/files/4787991/%40handsontable.zip)
Would you please have a look what's wrong?

Thank you.

**Comment by pnowak** [comment]
Hi @magic990619 

It's better to keep the same question in one place.

So please follow in this thread as I wrote above - https://github.com/handsontable/vue-handsontable-official/issues/177#issuecomment-643201997

**Comment by AMBudnik** [comment]
Hi @magic990619 I'm happy to announce that we just released Handsontable for Vue v 5.0.0 where we fix this issue.
Feel free to leave some feedback after testing.

We needed to push a quick fix in a patch so I'd recommend using 5.0.1.
