### ISSUE TITLE
get instance on vue, getSourceData(),  afterchange

### ISSUE THREAD

**Issue by carlospas** [handsontable/vue-handsontable-official#175]
### Description

 I need getSourceData() afterchange
ex.
const my_instance  = this.$refs.myTable.hotInstance;

console.log(my_instance.getSourceData())

### Steps to reproduce

1. vue.js:634 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'myTable' of undefined"
found in

---> <HotTable>
       <Root>

2. vue.js:1897 TypeError: Cannot read property 'myTable' of undefined

3. 

### Demo

https://jsfiddle.net/hmwus0xz/

### Your environment
* Vue wrapper version: last
* Handsontable version: last
* Browser Name and version: chrome
* Operating System: win10

**Comment by AMBudnik** [comment]
Hey @carlospas 

here's a tutorial on how to refer t the instance of Handsontable https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-vue-hot-reference.html

Following this example here https://jsfiddle.net/bj4un21z/ is an example of how to get `getSourceData()` on a button click and here https://jsfiddle.net/3q7hfw0d/ is a demo where you get` getSourceData()` result in the `afterChange` hook.
