### ISSUE TITLE
Partial Update 

### ISSUE THREAD

**Issue by gelinger777** [handsontable/vue-handsontable-official#176]
I have a problem with re-rendering the whole component, as I have to update cell data each 1-2 seconds. The problem is that the numbers mostly change in several cells and not all table. Is that possible to partially update the data ?

**Comment by pnowak** [comment]
Hi @gelinger777 

Can you attach a demo where we can reproduce the issue?
Please describe all the steps to do so.

Without it could be hard to fully understand your issue.

**Comment by gelinger777** [comment]
Hi @pnowak . I can't attach a demo. Imagine you have a initiated a  normal table with 4 rows and 4 columns. Now you want to update only cell 2:3 (second column and 3rd row) or several columns. How to do it? Currently we update the data value and the whole table rerenders . Isn't it possible to update only 2-3 cells instead of the whole data? 

We have a problem that the colwidth array is not working at all, and I have a clue that this could be the reason.

**Comment by pnowak** [comment]
Unfortunately, it's impossible to render only one cell. 

What do you mean `colWidth` array is not working at all? 
Doesn't render columns with appropriate width?

**Comment by gelinger777** [comment]
no, it's not.  probably because we use the free version (v6)

**Comment by pnowak** [comment]
I prepared a demo with a colWidths in Vue wrapper - https://codesandbox.io/s/col-width-n9pc2?file=/src/App.vue

It would be great if you could extend it to better reflect your issue.

**Comment by gelinger777** [comment]
Dear @pnowak  I can't provide you full test case , as we have a very complicated case where data comes each second from a pusher subscribe, and data is so that  float numbers length after dot change randomly, and because of that the table jumps left and right for 2-3 pixels. We have found other plugin which uses flexbox and divs , and we will abandon datatables. Thus I am closing the issue. Thank you for your time.
