### ISSUE TITLE
How to call parent's method in custom render component?

### ISSUE THREAD

**Issue by magikadev** [handsontable/vue-handsontable-official#177]
### Description
I am using custom render in hotTable.
In the custom renderer component, I want to call the parent's method when clicking an icon.
I tried to use event and props but both of them did not work.

Anyone please let me know solution.

### Demo
**Methods as props**
Home.vue 
```

<hot-table :data="hotTableData" :autoRowSize="false" :autoColumnSize="false">
         <hot-column title="Character" width="350">
             <first-column method="handleUp" hot-renderer></first-column>
          </hot-column>                     
</hot-table>

......................................................................
......................................................................

import FirstColumn from "./FirstColumn.vue";

......................................................................
......................................................................

methods: {
    handleUp(id) {
         console.log(id);
    }
}

```

FirstColumn.Vue
```
<template>
    <div>
          <div style="width: 30px;">
                <div style="height: 22px; line-height: 22px;">
                    <span v-on:click="upUserValue(value)"
                            class="glyphicon glyphicon-chevron-up"></span>
                </div>
                <label>{{value}}</label>
            </div>
    </div>
</template>
 
 <script>
 export default {
     props: {
         method: { type: Function },
     },
     data: function() {
         return {
             hotInstance: null,
             row: null,
             col: null,
             value: 0
         }
     },
     methods: {
         upUserValue(character_id) {
             this.method(character_id);
         }
     }
 }
 </script>
```
_Error: this.method is not a function_

**Events**

Home.vue

```
<hot-table :data="hotTableData" :autoRowSize="false" :autoColumnSize="false">
               <hot-column title="Character" width="350">
                   <first-column @onUpUserValue="handleUp" hot-renderer></first-column>
               </hot-column>
</hot-table>

......................................................................
......................................................................

method: {
    handleUp (event, id) {
            console.log(id);
     },
}
```

FirstColumn.vue

```
<template>
    <div>
          <div style="width: 30px;">
                <div style="height: 22px; line-height: 22px;">
                    <span v-on:click="upUserValue(value)"
                            class="glyphicon glyphicon-chevron-up"></span>
                </div>
                <label>{{value}}</label>
            </div>
    </div>
</template>
 
 <script>
 export default {
     props: {
         method: { type: Function },
     },
     data: function() {
         return {
             hotInstance: null,
             row: null,
             col: null,
             value: 0
         }
     },
     methods: {
         upUserValue(character_id) {
             this.$emit('onUpUserValue', character_id);
         }
     }
 }
 </script>

```
_No Result_

### Your environment
* Vue wrapper version: ^2.5.7
* Handsontable version: ^7.4.2
* @handsonetable/vue version: ^4.1.1
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by pnowak** [comment]
Hi @magic990619 

I would like to help you with that, but I will need a working demo first to clearly define the problem and offer a solution.

So could you extend our demo with custom renderer example - https://jsfiddle.net/6hwp7ofc/?

**Comment by magikadev** [comment]
Hi, Thank you for your message.
I tried to make a demo on codesandbox.
https://codesandbox.io/s/relaxed-elion-v7x8i
But it shows error even though I tried to show basic handsontable.
Would you please have a look?

**Comment by pnowak** [comment]
It works now. I think this was related to codesandbox bug - https://twitter.com/techniq35/status/1268011919748861953

So you can complete your demo.

**Comment by magikadev** [comment]
Okay. Thank you.
I will complete demo soon.

**Comment by magikadev** [comment]
Hello, @pnowak 
I completed demo. 
https://codesandbox.io/s/relaxed-elion-v7x8i
Please have a look.
Thank you.

**Comment by pnowak** [comment]
Thank you for the demo.

I suppose do you try to achieve something similar to this - https://github.com/handsontable/handsontable/issues/5977?

Unfortunately, it seems that it is impossible.

**Comment by magikadev** [comment]
Impossible?
Is there any way to call method in custom renderer component?

**Comment by pnowak** [comment]
As @aleksandra said in this forum thread - https://forum.handsontable.com/t/how-to-style-specific-column-headers/3064/2?u - we do not have any official API for column renderers. That is also for customer renderers.

Maybe I don't fully understand your requirements. When I'll `click` or `doubleClick` in the cell each column what should happen?

**Comment by magikadev** [comment]
I think this is not what I want to do. https://forum.handsontable.com/t/how-to-style-specific-column-headers/3064/2?u
What I want to do is like this.
When I click 'First click' and 'Second click', I want to put log of cell value on console.
But as you can see on demo, value is only logged on method of custom render. For calling parent method, it shows error. For easy understanding, I will add a short video of current demo status.
https://drive.google.com/file/d/1DbRLgFCqwjpuS7I735nTzwsDNoiKEiYw/view?usp=sharing
I hope this will help you to understand.
Thanks.

**Comment by magikadev** [comment]
Is it impossible?

**Comment by pnowak** [comment]
Hi @magic990619 

I have to consult with our Vue developer.
If I'll have any clue I come back.

**Comment by jansiegel** [comment]
@magic990619 The thing that I think you're trying to achieve is currently not possible due to a bug in the wrapper. It's already fixed on the `develop` branch (https://github.com/handsontable/vue-handsontable-official/issues/172), and will be out with the next `@handsontable/vue` release.

The fix allows passing props to custom renderers/editors, so it would be possible to pass `:method="handleUp"`, as you did in your demo, and then the `handleUp` method would be callable from inside of the renderer.

**Comment by magikadev** [comment]
Thank you, @jansiegel  and @pnowak . 
I tried on your codesandbox, it's working.
When will the next version be released?

**Comment by magikadev** [comment]
How can I use it on my application?

**Comment by pnowak** [comment]
We plan to release wrapper with a new version of Handsontable.
Handsontable 8.0.0 is at the stage of fixing all found regression issue.

Unfortunately, I can't give the precision date release. But I suppose it takes a few weeks.

**Comment by magic990619** [comment]
Few weeks... 
It's quite long time for me. I am working on a educational project and I have to use handsontable.
Is there any way to use @jansiegel 's commit?

**Comment by magikadev** [comment]
How can I use it on my website before release fixed version?

**Comment by pnowak** [comment]
As @jasonlfunk said in https://github.com/handsontable/vue-handsontable-official/pull/173#issuecomment-643133225 you have to `git clone` from `develop` branch and `npm i` && `npm run build`. 
Next, use `npm pack` and move `handsontable-vue.something.tgz` to your directory. 
In your folder make use `npm i handsontable-vue.something.tgz --save`. And you could normally import `import { HotTable } from '@handsontable/vue` in files.

**Comment by magikadev** [comment]
Hi, @pnowak , @jansiegel , @jasonlfunk

Passing props is working well on codesandbox.
https://codesandbox.io/s/clever-bardeen-jvt00
But it's not working on my project. I cloned the develop branch, build it and use it on my project.
Attached is the one that I built and use in the project. (/node_modules/@handsontable)
[@handsontable.zip](https://github.com/handsontable/vue-handsontable-official/files/4787991/%40handsontable.zip)
Would you please have a look what's wrong?

Thank you.

**Comment by pnowak** [comment]
Hi @magic990619 

Are you sure about codesandbox? I get a syntax error - `SyntaxError: [BABEL] /src/main.js: Unexpected token ; in JSON at position 12 (While processing: "base$0")`. 

<img width="796" alt="Zrzut ekranu 2020-06-17 o 12 26 12" src="https://user-images.githubusercontent.com/1555809/84887291-cfbb5d80-b095-11ea-876e-c8681f94d3e3.png">

**Comment by magikadev** [comment]
I think that's a bug of codesandbox.
Please try to save main.js again. Sometimes, it shows syntax error.
If you save main.js again, that error disappears.

**Comment by pnowak** [comment]
I tried a few times and the result is the same.
I asked for help our manager @aleksandra and unfortunately, she had the same error.

So could you check one more time that this demo works for you?

**Comment by magikadev** [comment]
https://drive.google.com/file/d/1X3nw-xUv_9FwYHK1WjCVOAjlo7AsPbC8/view?usp=sharing
Please have a look this video.

**Comment by pnowak** [comment]
If we remove/commented `getDebugInfo` and again save the file it starts working.

Nevertheless, because this is a custom implementation code review and guidance is reserved only to the client with an Extended support license. 

Could you send to `support@handsontable.com` your license key?

**Comment by AMBudnik** [comment]
It looks like this issue has been continued on the emails.
If it is valid please let me know. Till that time I am closing this issue.
