### ISSUE TITLE
Undo doesn't work with Insert and remove

### ISSUE THREAD

**Issue by aninde** [handsontable/vue-handsontable-official#181]
### Description
After `Insert operations` or `Remove columns` undo doesn't work. There is no such option at all in the context menu.
Undo work after removing rows from the contextMenu (but data are displayed wrong ), but not after removing columns.

![insert-undo](https://user-images.githubusercontent.com/30186818/88297576-58b25e00-cd00-11ea-9b17-98664f1c6876.gif)

### Steps to reproduce
Try to insert some rows and undo it.

### Demo

https://jsfiddle.net/js_ziggle/ejabsc37/1/

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.4.2
* Browser Name and version: Firefox 78, Chrome 83
* Operating System: macOS Catalina 10.15.6

**Comment by jansiegel** [comment]
Should be fixed with #185.

**Comment by wojciechczerniak** [comment]
Fixed and released in v5.0.1
