### ISSUE TITLE
Undo doesn't work corectly with trim rows

### ISSUE THREAD

**Issue by aninde** [handsontable/vue-handsontable-official#182]
### Description
Wrong data are displayed after undoing removal of all rows when we got trimmed Rows.
A keyboard shortcut does not work.

![undo-vue](https://user-images.githubusercontent.com/30186818/88299565-c95a7a00-cd02-11ea-969c-2915de00048b.gif)

Initial state: (left) After undoing of all rows  removal (right):
Row with (A3-B3) and row with A7-B7 was trimmed.

<img width="171" alt="Screenshot 2020-07-23 at 16 38 14" src="https://user-images.githubusercontent.com/30186818/88299746-03c41700-cd03-11ea-85ae-07fb73babe75.png"> <img width="171" alt="Screenshot 2020-07-23 at 16 38 34" src="https://user-images.githubusercontent.com/30186818/88299757-058dda80-cd03-11ea-99d3-2ca19d1cd739.png">

### Demo

https://jsfiddle.net/aninde/o1cvrzb7/1/

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.4.2
* Browser Name and version: Firefox 78
* Operating System: macOS Catalina 10.15.6

**Comment by jansiegel** [comment]
> A keyboard shortcut does not work.

Not an issue with the wrapper, works the same for vanilla `7.4.2`.

------

As for the main problem: should be fixed with handsontable/handsontable#185.

**Comment by mrpiotr-dev** [comment]
Due to
> A keyboard shortcut does not work.

is already solved in Handsontable v8, I split this issue into two separated problems:
- handsontable/handsontable#7542 - Undoing removed rows does not revert to initial state if some rows were trimmed
- handsontable/dev-handsontable#416 - Undoing removed rows add empty columns if at least one row was trimmed before
