### ISSUE TITLE
Issues with Handsontable-triggered data changes.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/vue-handsontable-official#185]
### Description
There's a problem with changing the data object (mostly adding rows/columns) from Handsontable triggering the `updateSettings` method, which sometimes results in improper behavior (e.g. https://github.com/handsontable/vue-handsontable-official/pull/180#issuecomment-663059991).

This scenario triggers the Handsontable's `loadData` method, which resets some of the plugins state, resulting in multiple issues.

### Steps to reproduce

1. https://github.com/handsontable/vue-handsontable-official/pull/180#issuecomment-663059991

### Demo
https://github.com/handsontable/vue-handsontable-official/pull/180#issuecomment-663059991

**Comment by jansiegel** [comment]
It looks like it fixes the bugs initially reported in #180:
- #182 
- #181

**Comment by jansiegel** [comment]
Closing -> to be developed in https://github.com/handsontable/vue-handsontable-official/pull/180.

**Comment by wojciechczerniak** [comment]
Fixed and released in v5.0.1
