### ISSUE TITLE
怎么获取handsontable中每个表格的样式？相关的api，属性，方法是什么？

### ISSUE THREAD

**Issue by lzn302846** [handsontable/vue-handsontable-official#187]
### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
HI @lzn302846 

We provide support only in English. While translating your query in the Google Translate I got this message

> How to get the style of each table in handsontable? What are the related APIs, attributes, and methods?

If that was your intentional question I wanted to ask if you'd like to be given a className of a table, column, row, cell?

**Comment by lzn302846** [comment]
是的，后台返回的表格样式是什么格式，前端在哪个API或方法中进行接收渲染页面！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "handsontable/vue-handsontable-official"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午2:17
收件人:&nbsp;"handsontable/vue-handsontable-official"<vue-handsontable-official@noreply.github.com&gt;;
抄送:&nbsp;"诗情、画意"<1259751620@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [handsontable/vue-handsontable-official] 怎么获取handsontable中每个表格的样式？相关的api，属性，方法是什么？ (#187)





 
HI @lzn302846
 
We provide support only in English. While translating your query in the Google Translate I got this message
  
How to get the style of each table in handsontable? What are the related APIs, attributes, and methods?
  
If that was your intentional question I wanted to ask if you'd like to be given a className of a table, column, row, cell?

**Comment by AMBudnik** [comment]
Hi @lzn302846 

if you still need some guidance please feel free to share a new ticket possibly in English as it removes possible misunderstanding or ambiguity.
