### ISSUE TITLE
8.0.0 bind data with vuex state not render

### ISSUE THREAD

**Issue by muei** [handsontable/vue-handsontable-official#189]
```
<template lang="pug">
  hot-table(
    ref="hot-table"
    :data="rows"
    :beforeChange="beforeChange"
    :afterChange="afterChange"
    width="100%"
    height="100%"
    )
```
The `rows ` if from vuex state, and a not empty array, then hook `beforeChange` will not trigger, but the `afterChange` triggered, and no rows rendered

**Comment by AMBudnik** [comment]
Hi @muei 

Please provide an online demo or a zipped project that will allow us to replicate the issue.

**Comment by muei** [comment]
```
handsontable: 8.0.0
@handsontable/vue: 5.0.1
```

If initial the data in the state, will render normaly, but not used by update.
https://codesandbox.io/s/handsontable-vue-800-501-g19c1?file=/src/App.vue

**Comment by AMBudnik** [comment]
Hi @muei 

in your demo, you defined a `data` variable but loaded an empty array instead. Here's the updated demo https://codesandbox.io/s/handsontable-vue-800-501-forked-tinzt. I added your data variable to the initialization settings. 

ps. Here's our Vuex example https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-vue-vuex-example.html. It shows how we cooperate with the Vuex state manager.

**Comment by muei** [comment]
@AMBudnik  I commented, if I set the data initial, it will display. My demo supported was when then component `mounted`, it set the data. The offical Vuex demo is used to set handsantable data to store, but this is not the common usage.

**Comment by AMBudnik** [comment]
Hi @muei 
We have some ideas on how to get to the bottom of this scenario. 

Handsontable uses `mounted()` to create a state of columns, so if you want to use `mounted()` to pass data you'd need to use the hint presented by the Vue team to add this.$nextTick function, like so

![image](https://user-images.githubusercontent.com/10757813/93763854-732a8a00-fc12-11ea-8c81-d7672474e5be.png)
src https://vuejs.org/v2/api/#mounted

* demo without $nextTick https://jsfiddle.net/AMBudnik/v9a34L7p/
* demo with $nextTick https://jsfiddle.net/AMBudnik/fav5g3uL/

ps. here's the link to the discussion https://github.com/handsontable/docs/issues/158

**Comment by muei** [comment]
Thanks for your reply, but this it's fix my issue. My issue is not reactive the vuex state, you can see my sample again, even if used inner $nextTick.
https://codesandbox.io/s/handsontable-vue-800-501-forked-dul0o?file=/src/App.vue

**Comment by muei** [comment]
The new version handsontable 8.1.0, vue-handsontable-official 5.1.0, the bug about the data stream vuex flows to the UI(handsontable), is still not fixed.

data -> vuex -> UI(hottable)

**Comment by AMBudnik** [comment]
Hi @muei have you tried the `$nextTick` way to handle data change within the `mounted()` hook?

**Comment by muei** [comment]
Yes, I have tried. And I updated the [demo](https://codesandbox.io/s/handsontable-vue-810-510-g19c1?file=/src/App.vue). 

And you can see my comments at state `data`.
```
//data, // if initial the data, will renderer normal
   data: [], // if initial as empty, set data after mounted, the render will not display data

```
Even I set the data twice with different method
```
mounted() {
    this.setData(data);
    this.$nextTick(() => {
      this.setData(data);
    });
  },
```
```
     setData(state, data) {
        state.settings.data = [...data];
        Vue.set(state.settings, "data", data);
      },
```

**Comment by AMBudnik** [comment]
Until we create the `mounted()` guide requested here https://github.com/handsontable/docs/issues/158 we should stick to the rule that 

> The page should begin by reminding that mounted event is fired after a component is rendered in DOM, so this is not the correct place to insert initial state. The initial state should be set in data or created.
> 
> This is in line with what other guides say:
> 
> Use mounting hooks if you need to access or modify the DOM of your component immediately before or after the initial render.
> 
> Do not use mounting hooks if you need to fetch some data for your component on initialization.

Source: https://www.digitalocean.com/community/tutorials/vuejs-component-lifecycle#mounting-dom-insertio

**Comment by muei** [comment]
Thanks a lot! And I have updated the demo!
