### ISSUE TITLE
Webpack Config issue

### ISSUE THREAD

**Issue by TJKoury** [handsontable/vue-handsontable-official#19]
Creating an alias seems to screw up handsontable-pro finding the plugins provided in handsontable:

```
* handsontable/3rdparty/walkontable/src in ./node_modules/handsontable-pro/commonjs/plugins/nestedHeaders/nestedHeaders.js, ./node_modules/handsontable-pro/commonjs/plugins/nestedRows/nestedRows.js
* handsontable/3rdparty/walkontable/src/overlay/_base in ./node_modules/handsontable-pro/commonjs/3rdparty/walkontable/src/overlay/bottom.js, ./node_modules/handsontable-pro/commonjs/3rdparty/walkontable/src/overlay/bottomLeftCorner.js
```
Really should have handsontable-pro be a complete drop in replacement for handsontable.

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same bug in v2.0.0-beta1+
