### ISSUE TITLE
How to use component with object data

### ISSUE THREAD

**Issue by muei** [handsontable/vue-handsontable-official#191]
### Description
How to use component with object data

### Code
```
<template lang="pug">
  hot-table(
    :data="data"
    :settings="settings"
    )
    hot-column(
      title="id"
      :width="150"
      )
      // customer-renderer-component
    hot-column(
      title="name"
      :width="150"
      )
</template>

<script>
import { HotTable, HotColumn } from "@handsontable/vue"
import Handsontable from "handsontable"

export default {
  components: {
    HotTable,
    HotColumn,
  },
  data() {
    colHeaders: ["id", "name"],
    data: [
       {
          id: 1,
          name: "N1",
        },
        {
          id: 2,
          name: "N2",
        },
        {
          id: 3,
          name: "N3",
        },
    ]
  }
}
</script>
```

### Your environment
* Vue wrapper version: ^4.0.0
* Handsontable version: ^7.3.0
* Browser Name and version: Chrome
* Operating System: Window 10

I wan to use custom component, but use the object data, if I define the `columns`, the component will not effective, can anyone help?

**Comment by AMBudnik** [comment]
Hi @muei 

here's an example with a custom renderer and object data https://jsfiddle.net/AMBudnik/0r7fzvhe/ 
What should that renderer do?

**Comment by muei** [comment]
@AMBudnik 
I mean, I wan to custom render the column with `hot-column`.
https://codesandbox.io/s/advanced-vue-hot-column-implementation-722-411-forked-t75fb?file=/src/App.vue

**Comment by AMBudnik** [comment]
Here https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-vue-hot-column.html is a tutorial with a working demo of a custom component. Have you tried it before?

**Comment by muei** [comment]
My data is object array, this is what i want to say

**Comment by AMBudnik** [comment]
@muei in the presented link there are 3 examples that use object data. They do not work if you try to implement them on your device/ in the project?

**Comment by muei** [comment]
If I use `HotColumn`, it only support data like this:
```
[
  ['a', 'b', 'c'],
  ['e', 'f', 'g'],
]
```
can't use like this:
```
[
  {name: 'a', 'title': 'b', label: 'c'},
  {name: 'e', 'title': 'f', label: 'g'},
]
```

**Comment by AMBudnik** [comment]
Hi @muei 

would that https://jsfiddle.net/AMBudnik/xLmqrazo/ meet your project requirements?

**Comment by muei** [comment]
@AMBudnik Thanks a lot!!!
