### ISSUE TITLE
Vue HotColumn not reactive immediate

### ISSUE THREAD

**Issue by muei** [handsontable/vue-handsontable-official#192]
### Description
In the demo, when use `columns` instead of `hot-column`, it's no problem.
When use `hot-column`, and renderer will not display immediate, if I update the *state* and save some times, it will render more than 1 columns which not defined with `hot-column`

### Demo
https://codesandbox.io/s/handsontable-vue-hot-column-implementation-742-411-cquo1?file=/src/App.vue

### Your environment
* Vue wrapper version: 4.1.1
* Handsontable version: 7.4.2
* vuex: 3.5.1

**Comment by AMBudnik** [comment]
Hi @muei 

>  and renderer will not display immediate

I do not see any use of a custom renderer in your demo. Is that the latest version of the demo?
