### ISSUE TITLE
Unable to build wrapper with new Vue 3.0.0

### ISSUE THREAD

**Issue by aninde** [handsontable/vue-handsontable-official#197]
### Description
It's impossible to build a Vue-Handsontable with Vue 3.0.0. Vue 3.0.0 isn't LTS yet.

After changing  `peerDependencies` and `devDependencies` to `"vue": "^3.0.0"` and updating ` vue-template-compile` to the latests version build failed.

Logs after `npm i` 
![image](https://user-images.githubusercontent.com/30186818/93870918-2d32fc00-fcce-11ea-8715-916c8df82c6d.png)

Logs after `npm run build`
![image](https://user-images.githubusercontent.com/30186818/93870986-43d95300-fcce-11ea-8717-49f767271314.png)

### Your environment
* Vue wrapper version: 5.0.1 +
* Handsontable version: 8.0.0
* Browser Name and version: Firefox 80.0.1, but it's not related
* Operating System: macOS Catalina 10.15.6
* Vue version: 3.0.0

**Comment by mrpiotr-dev** [comment]
Duplicate and/or part of the scope of handsontable/handsontable#7545
