### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by morkro** [handsontable/vue-handsontable-official#2]
Hello,

I've followed the [basic usage](https://github.com/handsontable/vue-handsontable-official#basic-usage) example and this project doesn't seem to work at all for me. Although, I've installed all required dependencies I still get the following error:

```
Uncaught Error: Cannot find module 'numbro'                      handsontable.js?732b:53
```

What am I missing? :)

**Comment by sunnirvana** [comment]
I met this issue in my case too. Compared webpack.config.js and package.json between vue-handsontable-office demo with my project. I did the followings:
1. Install expose-loader 
`npm install expose-loader --save-dev`

2.  add some loaders in **webpack.config.js**
```
module: {
        rules: [
            ......
            {
                test: require.resolve('numbro'),
                loader: 'expose-loader?numbro'
            },
            {
                test: require.resolve('moment'),
                loader: 'expose-loader?moment'
            },
            {
                test: require.resolve('pikaday'),
                loader: 'expose-loader?Pikaday'
            },
            {
                test: require.resolve('zeroclipboard'),
                loader: 'expose-loader?ZeroClipboard'
            }
        ]
    },
```

**Comment by jansiegel** [comment]
@morkro, @sunnirvana Have you tried following the configuration from the [/demo](https://github.com/handsontable/vue-handsontable-official/tree/master/demo) directory of this repo?

Also, please run `npm install` before building it with webpack, as all of handsontable's dependencies (including numbro) need to be ready for it to build properly.

**Comment by morkro** [comment]
Yeah, I have run `npm install` before but it still didn't work. I think the problem can be fixed by importing the full version of Handsontable instead:

```js
import Handsontable from 'handsontable/dist/handsontable.full'
```

**Comment by Luiz-N** [comment]
we got it working by modifying the import statements as follows:


```
import moment from 'expose-loader?moment!moment';
import numbro from 'expose-loader?numbro!numbro';
import pikaday from 'expose-loader?Pikaday!pikaday';
import ZeroClipboard from 'expose-loader?ZeroClipboard!zeroclipboard';
```

**Comment by robarchibald** [comment]
If you're using webpack v2, you'll need to use a different syntax. This is what I propose be added to the wiki to clear this up. Unfortunately, I can't submit a pull-request to the wiki.

----------------------
However, to make Handsontable work properly, we'll also need to expose all of the Handsontable's dependencies to the global context. The [webpack expose-loader](https://github.com/webpack-contrib/expose-loader) will be used to do this. It can be installed with:
```
npm install expose-loader
```
`webpack.config.js` must then be modified to expose dependencies with `expose-loader`. `webpack` v2 syntax is as follows:
```js
module: {
  rules: [
    {
      test: require.resolve('numbro'),
      use: [{
        loader: 'expose-loader',
        options: 'numbro'
      }]
    },
    {
      test: require.resolve('moment'),
      use: [{
        loader: 'expose-loader',
        options: 'moment'
      }]
    },
    {
      test: require.resolve('pikaday'),
      use: [{
        loader: 'expose-loader',
        options: 'Pikaday'
      }]
    },
    {
      test: require.resolve('zeroclipboard'),
      use: [{
        loader: 'expose-loader',
        options: 'ZeroClipboard'
      }]
    },    
  ]
}
```
See the [expose-loader documentation](https://github.com/webpack-contrib/expose-loader) for help or for `webpack` v1 syntax.

**Comment by jansiegel** [comment]
We've just released version `1.0.0`, which simplified the installation process: https://github.com/handsontable/vue-handsontable-official#basic-usage

Currently, there's need to import and expose any of the Handsontable dependencies, as they should work automatically.

Hope this helps!

**Comment by mekhami** [comment]
Unfortunately, this isn't "just working" out of the box. I have an existing Vue.js app.

I ran `npm install --save vue-handsontable-official`, and in my App component, `import HotTable from 'vue-handsontable-official`. I followed the rest of the instructions for using this component, but when I try to build I get errors such as:

```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-handsontable-official/src/HotTable.vue
Module build failed: Error: Couldn't find preset "es2015" relative to directory /path/to/my/node_modules/vue-handsontable-official
```
I manually added `babel-preset-2015` to my package.json, installed it, tried again, and I encounter:

```
ERROR in build.js from UglifyJs
Unexpected token: name (SettingsMapper) [./~/vue-handsontable-official/src/settingsMapper.js:3,0][build.js:64064,6]
```

There are still some serious problems in getting this thing to build.

**Comment by casoetan** [comment]
@jansiegel I'm having the same issue with @mekhami 
```bash
Module build failed: Error: Couldn't find preset "es2015" relative to directory "node_modules/vue-handsontable-official"
```

**Comment by kimond** [comment]
On my end, I have this issue whatever I put in my webpack.

```
Module not found: Error: Can't resolve './locale' in './node_modules/pikaday/node_modules/moment/src/lib/locale'
```

**Comment by ismet** [comment]
I'm getting exactly the same error.

```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-handsontable-official/src/HotTable.vue
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\DEV\\HYDROOPT\\SWH\\webclient\\node_modules\\vue-handsontable-official"
    at C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\DEV\APP\webclient\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\DEV\APP\webclient\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\DEV\APP\webclient\node_modules\babel-loader\lib\index.js:175:20)
 @ ./node_modules/vue-handsontable-official/src/HotTable.vue 8:0-118
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/project.vue
 @ ./src/components/project.vue
 @ ./src/routes.js
 @ ./src/main.js
```

**Comment by cordeirovs** [comment]
I got it working with `npm i -S babel-preset-es2015`.

**Comment by kimond** [comment]
I tried again and everything works fine.

**Comment by mihaiconstantin** [comment]
Same issue as @mekhami. Adding `npm i -S babel-preset-es2015` solved.

**Comment by awulkan** [comment]
Installing `babel-preset-es2015` worked for me as well, BUT I get a warning that I shouldn't be installing it because they recommend `babel-env` now. Someone should probably look into this.

**Comment by mismith** [comment]
Anyone here to tackle this?

**Comment by BBaek** [comment]
I installed babel-preset-es2015. But when i try build, I got an error such as:

<pre><code>This dependency was not found:

* handsontable in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-handsontable-official/src/HotTable.vue, ./node_modules/vue-handsontable-official/src/settingsMapper.js and 1 other</code></pre>

**Comment by kimond** [comment]
@BBaek As stated in the release information of the last version https://github.com/handsontable/vue-handsontable-official/releases/tag/1.1.0. You need to install handsontable **separately**.

**Comment by BBaek** [comment]
@kimond I installed 2 modules separately by npm. But same errors.
<pre><code>
├─┬ handsontable@0.35.1
│ ├── moment@2.20.1
│ ├── numbro@1.11.0
│ └─┬ pikaday@1.5.1
│   └── moment@2.20.1 deduped
├── vue-handsontable-official@1.1.0
</code></pre>

**Comment by AMBudnik** [comment]
Sorry for the delay. We will be updating the wrapper in Q2. Now as one of our devs tested the wrapper does not install itself properly

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mismith** [comment]
Works for me, thanks @jansiegel!

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
If you have a problem to install our wrapper, then follow installation guide.
