### ISSUE TITLE
How to use validator when use HotColumn

### ISSUE THREAD

**Issue by muei** [handsontable/vue-handsontable-official#200]
If use the Vue/React component like HotColumn, how to use `validator`? Should I implement by self?

**Comment by AMBudnik** [comment]
Hi @muei 

Here's an example https://jsfiddle.net/cL1fdjym/ of a validator added to a single column using `HotColumn` syntax.
If you'd like something more than that please let me know.

**Comment by muei** [comment]
Thanks for reply, but in the demo, should focus the cell input then trigger the vadlitor, can not auto validate.

**Comment by AMBudnik** [comment]
By default, validator is triggered when a cell is changed. It happens for the cell that is changed, not for all the values. Can you share an example (or a drawing) what would be an expected behavior?

**Comment by muei** [comment]
I share a common usage case, user import a excel and set the type of column, and hope handsontable show invalid cells which not match the type immediately, this will helped to correct the value.

**Comment by AMBudnik** [comment]
Oh, OK, I see it now. 
You can use the [validateCells](https://handsontable.com/docs/8.1.0/Core.html#validateCells) on the data load. Here's an example https://jsfiddle.net/u0vf8mdc/
