### ISSUE TITLE
About cell validator used by vuex

### ISSUE THREAD

**Issue by muei** [handsontable/vue-handsontable-official#203]
Also https://github.com/handsontable/vue-handsontable-official/issues/200 fixed to validate cells. But the `validateCells` methods will validate all cells, the performance is too bad.
In addition, if use vuex to reactive the data, the validator is failure. For example:
```
beforeChange() {
  // call vuex mutation
  this.updateCells()
  return false
}
```
It may be necessary to provide a method to validate the specified cell(s).

**Comment by AMBudnik** [comment]
Hi @muei 

that topic has been raised on the main issue board here https://github.com/handsontable/handsontable/issues/3276 
I will update you once we make any further progress with that task.
