### ISSUE TITLE
How to add filtering to the table (question)

### ISSUE THREAD

**Issue by ebdev11** [handsontable/vue-handsontable-official#205]
Given the following example: 
https://jsfiddle.net/api/post/library/pure/
 
How do I add the filtering to the table ? I tried adding filters: true, to the settings but nothing happens. Am I missing something ? Also I couldn't find anything on the vue wrapper documentation. 

### Your environment
* Vue wrapper version: 4.1.0

**Comment by AMBudnik** [comment]
Hi @ebdev11 

Your demo did not save. If I click it - it is empty. With JSFiddle generated from our website, you need to click SAVE or FORK to save the new URL.

However, I think that I know what might be the problem. The `filters: true` is the right option to choose. However, you also need to have columns' header (`colHeaders` or `nestedHeaders`) and the `dropdownMenu` enabled. Here https://jsfiddle.net/handsoncode/Ljtdrxy8/ is a demo using Vue, and here is my code 

```js
hotSettings: {
          data: Handsontable.helper.createSpreadsheetData(6, 10), //data
          colHeaders: true,
          dropdownMenu: true,
          filters: true
}
```

**Comment by ebdev11** [comment]
@AMBudnik Thank you so much for the quick response, and I'm sorry about the JSFiddle. I was in fact missing the  colHeaders: true, dropdownMenu: true and I was using and older version of the handsometable. 
Now I'm trying to create a function to validate what the user enters on a cell and after that populate another. I cannot find any info on how to get the data of a specific cell or how to call a method. Im using the vue dev tools and when I type on a cell there are not events happening. Can you provide and example of how to call a method? I create the following fiddle to illustrate a part of what I'm trying to accomplish (not sure that the after-begin-editings is the best "event" to accomplish this).

https://jsfiddle.net/28wczqfj/4/

**Comment by AMBudnik** [comment]
Sure. Here https://jsfiddle.net/handsoncode/Lcqukzjy/ is your demo updated.

Hadsontable provides a lot of different hooks. When data changes and you want to gather the information about the change you can use the [`afterChange`](https://handsontable.com/docs/8.2.0/Hooks.html#event:afterChange) hook. I've placed that hook inside the demo above (lines 13-18). 

Once you change any cell's value in that demo the console of your browsers will print a string representation of the change. In our example 'edit' and below that an array that holds coordinates of the changes cell and its old and new value.

![image](https://user-images.githubusercontent.com/10757813/105466849-24aafc00-5c95-11eb-9bd4-47e72a787271.png)

![afterChange](https://user-images.githubusercontent.com/10757813/105467028-6340b680-5c95-11eb-9323-d23043364f9d.gif)

As in your demo, a dataset is an object the 2nd parameter is not a number (column index) but a column key.

When it comes to changing one cell after retrieving information that some other cell changed I highly recommend checking our blog post about cell dependencies -https://handsontable.com/blog/articles/2016/4/expand-your-app-with-cell-dependencies. We share a lot of examples using different cell types. 

You will see that in those examples we use [`beforeChange`](https://handsontable.com/docs/8.2.0/Hooks.html#event:beforeChange) hook as it fires before actually doing the change. In the process of building your knowledge about our hooks, I propose to try them both.
