### ISSUE TITLE
Vue wapper not render data

### ISSUE THREAD

**Issue by robertovaldesperez** [handsontable/vue-handsontable-official#207]
### Description
I have this code:
`<hot-table
      v-if="!listLoading"
      v-loading="listLoading"
      :data="page.content"
    />`

`computed: {
    ...mapState('desktop', {
      nextFilter: state => state.nextFilter,
      page: state => state.page
    })
  },
  created() {
    this.nextFilter.filter.porfolioId = 1098
    this.nextFilter.filter.topTen = false
    this.nextFilter.pageRequest.size = 50
    this.loadCurrentPage()
  }`
### Steps to reproduce

1. If I remove this line : v-if="!listLoading" (listLoading=false after load data from rest api)
Vue wrapper not render data

I think it is necessary to have the data loaded before displaying handsontable. How can I refresh the handsontable after loading the data?

### Your environment
* Vue wrapper version:^5.1.0
* Handsontable version: ^8.2.0
* Browser Name and version: chrome Versión 87.0.4280.141
* Operating System: windows 10

**Comment by AMBudnik** [comment]
Hi @robertovaldesperez 

would you be able to send me the project (the part with Hadsontable) zipped on my email support@handsontable.com? 
ps. have you tried our vuex tutorial https://handsontable.com/docs/8.3.0/frameworks-wrapper-for-vue-vuex-example.html?
