### ISSUE TITLE
nested rows have incorected row counts

### ISSUE THREAD

**Issue by rupertqin** [handsontable/vue-handsontable-official#209]
### Description
nested rows have incorected row counts

### Steps to reproduce
1. set nestedRows: true
2. set nested data

### Demo
https://jsfiddle.net/rqbn0vec/
the counts of the rows should be 11, but there is 5.

### Your environment
* Vue wrapper version: v2.6.12
* Handsontable version:v8.3.1
* Browser Name and version: Chrome v88.0.4324.146 
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/handsontable #7587](https://github.com/handsontable/handsontable/issues/7587) via [**ZenHub**](https://www.zenhub.com/)
