### ISSUE TITLE
Render a component inside a Custom Render

### ISSUE THREAD

**Issue by alexon1234** [handsontable/vue-handsontable-official#21]
Currently, I am trying to create a custom render cell where the user will be able to upload some files. But I am facing the problem to render an upload component inside each cell of the column.

Does anyone have an idea of how to achieve this??

Thank you so much

**Comment by AMBudnik** [comment]
Hi @alexon1234 

if that helps I have an example that uses vanilla version http://jsfiddle.net/handsoncode/bra4qfy7/

**Comment by alexon1234** [comment]
Cześć,
So then... I understand that there is nothing implemented to link a cell to a Vue component. 
Like a custom renderer but instead of writing all the code inside of the custom renderer function just like it to a component

**Comment by AMBudnik** [comment]
Cześć :)

The cell with a custom renderer can take anything that uses HTML. You just need to check if the height/width are equal to the content that you want to display. You can refer to the context via `td.innerHTML` option.

Do you have any particular component on your mind?

**Comment by alexon1234** [comment]
I have implemented a uploader cell in order to upload a file for each row

**Comment by mrpiotr-dev** [comment]
Hi @alexon1234,
At this moment functionality `component in renderer` is not supported.
I think we can close this issue. Feel free to reopen if you find any solution on this subject.
