### ISSUE TITLE
Upgrade to Vue 3?

### ISSUE THREAD

**Issue by meSingh** [handsontable/vue-handsontable-official#211]
I want to know if there are any plans for upgrading this integration to Vue 3 in near future. Or if there is any possible way to use it right now, other than using Handsontable directly as vanilla js implementation?

**Comment by AMBudnik** [comment]
Hi @meSingh 

We've transfered issues from this board to the main Handsontable board as a part of the monorepo project.

This subject is mentioned here https://github.com/handsontable/handsontable/issues/7545 
It hasn't been scheduled yet but the issue will get updated once we add it to the milestone.
