### ISSUE TITLE
How to load data with ajax?

### ISSUE THREAD

**Issue by dmitriy-01** [handsontable/vue-handsontable-official#22]
Could someone please explain or show how to use this example https://docs.handsontable.com/0.34.5/tutorial-load-and-save.html with Vue?

I'm using Laravel 5.5 with Vue and trying to load and update data with ajax. Basic example with static data https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide works fine for me.

Any help appreciated.

Thanks.

**Comment by richardkeep** [comment]
Am faced with the same challenge. Did you manage to solve this issue?

**Comment by dheeraj-wirecard** [comment]
Hi ,
It's clearly mentioned in the documentation. 
<hot-table ref="hotTableComponent"></hot-table>

use refs to get the handsontable instance.
this.$refs.hotTableComponent.hotInstance.loadData(newdata);
