### ISSUE TITLE
Cannot read property 'view' of undefined

### ISSUE THREAD

**Issue by treasureDouDou** [handsontable/vue-handsontable-official#24]
When I click the right mouse button, select any border in the table line, and the error message will be prompted

![image](https://user-images.githubusercontent.com/21187862/32881411-23c1f638-caec-11e7-9c91-51e2c5c34074.png)

**Comment by mrpiotr-dev** [comment]
Hi @treasureDouDou,
Could you send us more information about versions of Handsontable, wrapper, Vuejs?
I've prepared an example: https://codepen.io/swistach/pen/Zooewb
Could you confirm that this issue still occurs?

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there is more than a month without any updates.
However, @treasureDouDou  let us know if you still get the log.
