### ISSUE TITLE
TS2307: Cannot find module 'vue-handsontable-official'.

### ISSUE THREAD

**Issue by davidm-public** [handsontable/vue-handsontable-official#25]
Vue2 / Typescript project:

```
  import Vue from 'vue'
  import { Component, Prop, Watch } from 'vue-property-decorator'
  import HotTable from 'vue-handsontable-official'
```

error: TS2307: Cannot find module 'vue-handsontable-official'.

Relevant dependencies:

    "vue": "^2.5.3",
    "vue-handsontable-official": "^1.0.0",
    "typescript": "^2.6.1",
    "webpack": "^3.8.1",

**Comment by 3dots** [comment]
Same issue here. If I try to use typescript in a .vue file (within <script lang="ts"> section) the error shows up when compiling with webpack.

**Comment by GiuMagnani** [comment]
Did you solve it?

**Comment by AMBudnik** [comment]
Hi guys,

sorry for the delay. 

I have to say that we did not have any spare time to update the wrappers so the following issues may occur. 

We are planning (and I really hope that we'll be able to reach this goal) to update the wrappers and fix some smaller issues in Q2 this year.

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
Hi @davidm-public, @3dots, @GiuMagnani.
Currently, we don't support TypeScript officially for `@handsontable/vue` nor `@handsontable-pro/vue`.
We are open to any pull request from you.

**Comment by jansiegel** [comment]
The wrapper is in the process of being rewritten to Typescript (#74), so I think this issue should be resolved soon.
