### ISSUE TITLE
Can't define my customRenderer

### ISSUE THREAD

**Issue by aZilberstein** [handsontable/vue-handsontable-official#27]
Hello team, I'm having an issue with the following workflow:

1) Importing vue-handsontable-official into my component.
` import VueHandsonTable from 'vue-handsontable-official';
`
2) Trying to register a customRenderer by calling Handsontable.renderers.registerRenderer with all the necessary arguments and then getting:
> ReferenceError: Handsontable is not defined

3) Then trying to import Handsontable explicitly: 
` import Handsontable from 'handsontable';`

and then getting: 
> [Vue warn]: Error in callback for watcher "data": "Error: No registered renderer found under "MyRenderer" name"

I also tried registering my custom renderer in my entry JS file, to no avail. 

After all I tried all possible combinations and ended up with such a beginning of a component: 

```
import HotTable from 'vue-handsontable-official';
import Vue from 'vue';
import Handsontable from 'handsontable';
Handsontable.renderers.registerRenderer('MyRenderer', function (instance, td, row, column, prop, value, cellProperties) {
    td.innerText = moment.unix(value).format('DD.MM.YYYY hh:mm:ss');
    return td;
});
```

I managed to succeed when trying to make custom renderers for Handsontable **without** Vue and this wrapper component, but how do I add to custom renderers **with** vue-handsontable-official? The documentation isn't clear about this moment, so one would suppose that the process of registering of custom renderers is no different than in "vanilla JS" version, but maybe there's some extra trick into it?

Would be grateful for any help. Thanks in advance.

**Comment by aZilberstein** [comment]
UPDATE: Solely for experimental purposes I got into the HotTable.vue component in _node_modules/vue-handsontable-offical/src_ and tried to declare my custom renderer RIGHT AFTER the handsontable import:

```
import Handsontable from 'handsontable';
Handsontable.renderers.registerRenderer('MyRenderer', function (instance, td, row, column, prop, value, cellProperties) {
   td.innerText = moment.unix(value).format('DD.MM.YYYY hh:mm:ss');
   return td;
});
import SettingsMapper from './settingsMapper';
```

And it worked! Thus it means that the component's internal Handsontable can not be overridden as it happens independently from my explicit import in the entry file or anywhere else...What would be the proper solution to impact the Handsontable config that the component retrieves with the package? 

Sorry if my question seems silly. Thanks for you help in advance.

**Comment by GreenMelon** [comment]
tyr to use
```
const Handsontable = require('handsontable');

```
instead of
```
import Handsontable from 'handsontable';

```

**Comment by aZilberstein** [comment]
@GreenMelon thanks for you reply. 

The import is made within the vue-handsontable-official package's component...Not in my project's files. Would it be appropriate if I forked the package to rewrite the import in this single component, just for my needs? 

Perhaps it would be "cleaner" if there were some options in the vue-handsontable-official component configuration...What do you think? 

As of now, I manipulate the table instance methods by giving my HotTable component a **ref**, say, "myTable", and then calling its Handsontable instance's methods like this:

`this.$refs.myTable.table.addHook`

Not sure if it's the best way...

**Comment by kieranongh** [comment]
Bump. Exactly the same problem and exactly the same hack solved it (Registering the custom renderer in HotTable.vue)

**Comment by andysongs** [comment]
@aZilberstein Hi Andy, I think I have the same problem as yours.
I tried the way you mentioned bofore:
```js
import Handsontable from 'handsontable';
Handsontable.renderers.registerRenderer('MyRenderer', function (instance, td, row, column, prop, value, cellProperties) {
   td.innerText = moment.unix(value).format('DD.MM.YYYY hh:mm:ss');
   return td;
});
import SettingsMapper from './settingsMapper';
```
It seems not working, and I don't know what to do next.

Could you please give me some tips to help me run it on?
Thanks a lot xD

**Comment by aZilberstein** [comment]
@andysongs Hey, after all I figured that with _vue-handsontable-official_ wrapper it will not be possible for me to re-use these renderers in a convenient manner...
So I resorted to such a solution:
1) Created a mixin component with my "tableCellRenderers" which I called "TableUtils.vue"
2) I import this mixin into every component that needs those table cell renderers
3) For each table column in table config I write smth like "renderer: this.booleanCellRenderer" etc...

I know it's not very convenient and requires a lot of boilerplate but here we are :)
We also did another dirty hack with this handsontable Vue wrapper in our project: we [forked](https://github.com/aZilberstein/vue-handsontable-official) the vue-handsontable-official project and added an "instance" data field in HotTable.vue component, so we could access the table Handsontable instance with this.$refs.myTable.instance and do some manipulations there...but it's not for defining reusable renderers, as it seems that every HotTable.vue component has its' own instance of Handsontable entity imported...

Alternatively, you could probably try to write some kind of your own wrapper or use the "Vanilla JS" version of this table...

**Comment by andysongs** [comment]
@aZilberstein Thanks for teaching me!
Your method works well, even though, as what you say, not very elegant.

After I solved the problem by your method, another thing began to bother me.
It is if I want to rewrite the style of this table, there are three different place to set: CSS, initialize options and the customRenderer(). But I found that the same property may have different performance.

e.g. The rowHeights is not the real height of the ```<td>``` tags, it might because the computing behind the style box-sizing. Then I try to write some CSS to overwrite, but it breaks some other default styles. So sometimes I also have to go into the renderer function, write something like ```td.style.padding = 12px```.

In addition, it seems like that the custom renderer function will break the options like ```columnSorting: true```, so what if I want to use these features, by ```addEventListener()```? Or, how can I insert a button that calls the ```table.sort()``` method?

My questions might be stupid. Thanks for helping me.

BTW, I didn't know what the "Vanilla JS" is until you told me that. A hiahia, It reminds of the [nocode](https://github.com/kelseyhightower/nocode) repository xD

**Comment by mrpiotr-dev** [comment]
Hi @aZilberstein.
Thank you for your sharing.
I would like to attach one example extra: https://codepen.io/swistach/pen/xjJVYd

@andysongs Could you open new issue with a question about column sorting? It will be easier to find a solution by others.

**Comment by mekhami** [comment]
@swistach in the example provided iny our codepen, how would you go about registering multiple different renderers? i have many different custom renderers in my application. Would you just cobble all of these together into one custom renderer?

**Comment by mrpiotr-dev** [comment]
Hi @mekhami,
`renderer` is a single function, so you have to register them one at a time.
```
Handsontable.renderers.registerRenderer('custom-renderer', function (hotInstance, td, row, column, prop, value, cellProperties) {
  ...
});

Handsontable.renderers.registerRenderer('custom-renderer2', function (hotInstance, td, row, column, prop, value, cellProperties) {
  ...
});

Handsontable.renderers.registerRenderer('custom-renderer3', function (hotInstance, td, row, column, prop, value, cellProperties) {
  ...
});
```

You can also extends them like here: https://codepen.io/anon/pen/VdxBzW

**Comment by stanleyxu2005** [comment]
I ran into the same problem and realized, that I tried to set type='CustomTypeRenderer', this will never work.

Here is the correct way:
```javascript
import Handsontable from 'handsontable'

function CustomTypeRenderer(instance, td, row, col, prop, value, meta) {
  return Handsontable.renderers.NumericRenderer.apply(this, arguments)
}
Handsontable.renderers.registerRenderer('CustomTypeRenderer', CustomTypeRenderer)
Handsontable.cellTypes.registerCellType('custom-type', {
  renderer: CustomTypeRenderer,
});
```

In the Hottable config, you can specify `type='custom-type'` for column then. If you just want to change a renderer, then `renderer='CustomTypeRenderer'`.
