### ISSUE TITLE
my handsontableInput is too wider

### ISSUE THREAD

**Issue by ccmiaomiao** [handsontable/vue-handsontable-official#28]
i just setted 
self.hotSettings = {
          data: self.dataSource // and there is just 1 col 1 row1
}
when i double click to edit the cell ,the handsontableInput>textarea is too wider than the table...
so , how can i set some style or settings can fix this
thx very much for helping~~

**Comment by AMBudnik** [comment]
Hi @ccmiaomiao 

the issue is already reported at https://github.com/handsontable/handsontable/issues/3815
it looks like it's the vanilla version

**Comment by ccmiaomiao** [comment]
@AMBudnik roger that , thx
