### ISSUE TITLE
how to dispaly the table menu (right click) on the top layer,if this in a dialog box?

### ISSUE THREAD

**Issue by SWaiter** [handsontable/vue-handsontable-official#29]

**Comment by SWaiter** [comment]
I solved this problem ，I set the css of class htMenu ，setting z-index is a big int number and !important ,ps:
.htMenu{
    z-index: 214748364 !important;
  }
ths

**Comment by mrpiotr-dev** [comment]
Hi @SWaiter,
Thank you for sharing the issue report of incompatibility. I'm glad that you found a workaround.
Your comment will be helpful for the community.

**Comment by desperado0807** [comment]
Thanks, it really works~
