### ISSUE TITLE
Redistributable build?

### ISSUE THREAD

**Issue by davidwallacejackson** [handsontable/vue-handsontable-official#3]
The install process for this wrapper is pretty complicated -- it seems like it'd be easier if the wrapper had a precompiled distribution, like the main HOT library. The dependencies (including HOT itself) could be provided as [externals](https://webpack.js.org/configuration/externals/) and listed as peerDependencies.

**Comment by jansiegel** [comment]
@davidwallacejackson, since version `1.0.0` the installation process is much easier: https://github.com/handsontable/vue-handsontable-official#basic-usage

Basically, importing 
```
import HotTable from 'vue-handsontable-official';
```
should be enough to get going, all the Handsontable dependencies should work automatically.

**Comment by davidwallacejackson** [comment]
Unfortunately, I'm still getting the same errors, and I need to manually install and expose the dependencies. I checked the installed version of vue-handsontable-official, and it still only has the package source -- no compiled distribution. Am I doing something wrong?

**Comment by jansiegel** [comment]
@davidwallacejackson, we just did exactly what you described in your initial post :)
`@handsontable/vue` (and `@handsontable-pro/vue` for the Pro version) packages include a pre-built bundle, pre-configured for the CE or Pro packages, with `handsontable` (or `handsontable-pro`) listed as a peer dependency.

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same problem in v2.0.0-beta1+
