### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/projects/vs-vue2/node_modules/vue-handsontable-official"

### ISSUE THREAD

**Issue by nicolasxu** [handsontable/vue-handsontable-official#31]
Error when importing the hottable:

  import HotTable from 'vue-handsontable-official';

will result the following error:

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/shenxinxu/projects/vs-vue2/node_modules/vue-handsontable-official"

How to fix it?

**Comment by huangsinchu** [comment]
`npm install babel-cli babel-preset-es2015`

**Comment by karamasoff** [comment]
Isn't it a way to just configure the `babel-preset-env` to make it work fine ?
On babel website the use of `babel-presets-es20**` are discouraged in profit of `babel-presets-env`.

**Comment by mismith** [comment]
Agreed, should probably change this to use `env` instead of `es2015`

**Comment by ziveen** [comment]
**Module build failed: Error: Failed to find '~handsontable/dist/handsontable.full.css'**. I got this problem.But the file is in the folder.

**Comment by titan83** [comment]
@Luefeng, https://github.com/handsontable/vue-handsontable-official/pull/32
May be after your message dev team apply this pull request.

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by masvin** [comment]
I had the same problem.

Following the instalaltion guide
https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

_npm install vue-handsontable-official_
_npm install handsontable_

 ERROR  Failed to compile with 1 errors                                                                              11:29:28 AM
 error  in ./node_modules/vue-handsontable-official/src/HotTable.vue

Module build failed: Error: Cannot find module 'babel-preset-es2015' from '<my-project>\node_modules\vue-handsontable-official'

I'm using Babel version 7 so i installed  

_npm install babel-preset-env --save-dev_

The error was still present, so i changed the **.babelrc** file in node_modules/vue-handsontable-official

{
 "presets": ["env"]
}

then 
npm run serve
for me it works! :)

 DONE  Compiled successfully in 1734ms  11:36:44 AM

**Comment by jansiegel** [comment]
@masvin, if you use the latest version from `@handsontable/vue`, this should no longer be an issue: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-with-Handsontable-CE

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same bug in v2.0.0-beta1+
