### ISSUE TITLE
Nested rows with handsontable in Cell regarding vue-handsontable-official?

### ISSUE THREAD

**Issue by zhaoshaomeng** [handsontable/vue-handsontable-official#33]
Hi,

I am new to vue-handsontable-official, and now would like to get the simialr result as below link shows:
https://jsfiddle.net/59dz92jh/55/

The above is using the handsontable directly, NOT the vue-handsontable approach, how should I do in vue-handsontable-official context?

Thanks for kind help!

**Comment by xeoshow** [comment]
I am the same team with the issue owner. And we have already made it work with PRO version, so the nested rows feature is available now ...

**Comment by AMBudnik** [comment]
This conversation has been redirected to email support channel.
