### ISSUE TITLE
webpack build error 

### ISSUE THREAD

**Issue by superpig** [handsontable/vue-handsontable-official#36]
![image](https://user-images.githubusercontent.com/5066518/35610934-32f402a2-069e-11e8-9227-128ab6180001.png)
when I update vue-handsontable-official@1.1.0, the webpack throw the error, Could author build the source code of vue-handsontable-official before publish the npm package ?

**Comment by AMBudnik** [comment]
Thank you for sharing. We will check that.

**Comment by superpig** [comment]
@AMBudnik  I have found that other version has the same problems,  could you fix it as soon as possible ? I want to use it in production.

**Comment by superpig** [comment]
I have solved it by adding webpack config, but it is not the best way, users shouldn't hack it:
```js
{
   test: /\.js$/,
   loader: 'babel-loader',
   include: [
     path.resolve(__dirname, './node_modules/vue-handsontable-official')
   ]
}
```

**Comment by rswheeldon** [comment]
Thanks. This does look like a dirty hack but it worked for getting this working for me. Previous behaviour on IE11 was to display an error saying "SCRIPT1002: Syntax error". Adding resolve('./node_modules/vue-handsontable-official') to the webpack conf fixed it.

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same problem in v2.0.0-beta1+
