### ISSUE TITLE
Rows missaligned when fixed column is used with cells that contain wrapped text

### ISSUE THREAD

**Issue by michaelkrnac** [handsontable/vue-handsontable-official#37]
I use 

- "handsontable-pro":"^1.15.1",
- "vue-handsontable-official": "^1.1.0",
- Chrome 61 on Windows

If i have wrapped text in the cells and fixed columns i get a missalignmend in the rows at the point between fixed and rest columns.

The problem is described in the following issue:
https://github.com/handsontable/handsontable/issues/3239

But the fix does not work for me with vue-handsontable-official.

It can be reproduced with the vue-handsontable-official demo.
https://github.com/handsontable/vue-handsontable-official/tree/master/demo

Change the demo in the folliwing way:

Push more content into the cells.
` row.push('[' + i + ', ' + j + ']' + 'sadadadadadadadadasdasdsd asdasd aasd asd asd sad');`

Set fixed width to the columns so the text wrapps:
`colWidths: [80, 100, 150, 80, 200, 200, 250, 100, 150, 250, 200, 400, 60, 130, 300, 300, 200, 300],`

Fix the columns:
`fixedColumnsLeft: 3,`

Scroll right and down than the missallignment appear.

Add 
`autoRowSize: true,`
to fix the problem. 

But the problem still appears.

**Comment by AMBudnik** [comment]
Hi @michaelkrnac 

Can you record the behavior? I am not able to replicate it on my local machine. I am also trying it on Chrome (but v63) on Windows.

**Comment by michaelkrnac** [comment]
Hi AMBudnik,

here is the record.
![handsontablevuebug](https://user-images.githubusercontent.com/3944657/35910961-a8015d60-0bf8-11e8-9ac5-11553ed55534.gif)

And here are the hotSettings i use.
It is also reproducable with Firefox 58.0.1 on Windows.
````
   hotSettings: {
          data: function(rows, columns) {
            const result = [];
            for (let i = 0; i < rows; i++) {
              let row = [];
              for (let j = 0; j < columns; j++) {
                row.push('[' + i + ', ' + j + ']' + 'sadadadadadadadadasdasdsd asdasd aasd asd asd sad');
              }
              result.push(row);
            }
            return result;
          }(40, 40),
          colHeaders: true,
		  colWidths: [80, 100, 150, 80, 200, 200, 250, 100, 150, 250, 200, 400, 60, 130, 300, 300, 200, 300],
   		autoRowSize: true,
      		fixedColumnsLeft: 3,
        }
````

**Comment by AMBudnik** [comment]
Thank you for sharing.

I have replicated the issue on Firefox 58. However, I have Chrome 63 that does not reflect the same issue.

**Comment by michaelkrnac** [comment]
I have the problem also with Chrome 64.

**Comment by AMBudnik** [comment]
Hi guys. I have tested the following code http://jsfiddle.net/handsoncode/uftbx0oy/ with Handsontable v `0.38.1` and it seems to work on all browsers on OSX and WIndows. Can you check it?

**Comment by mrpiotr-dev** [comment]
Hi @michaelkrnac.
This bug occurs in main library handsontable/handsontable#3618. There you can track work progress.

**Comment by AMBudnik** [comment]
Please track progress to https://github.com/handsontable/handsontable/issues/3618
We close tickets that are duplicates.
