### ISSUE TITLE
infinite update loop in watcher with expression "settings" with minSpareRows > 0

### ISSUE THREAD

**Issue by abrim** [handsontable/vue-handsontable-official#38]
When I set minSpareRows=1 as a prop or in hotSettings, I get an infinite update loop warning, a large number of blank rows are added to the table and multiple 'loadData' events are emitted.

**Comment by AMBudnik** [comment]
Hi @abrim 

I was not able to replicate the issue using the `demo` folder from this repository on my local machine. Have you just added the `minSpareRows` > 0 or something else as well? Or maybe you have performed some operations? I was just checking the scrolling and editing.

**Comment by abrim** [comment]
The issue seems to only occur when I have a calculated column ( i.e. with data:function(row,val) ) - even if the column just returns a constant.

**Comment by AMBudnik** [comment]
Can you share your data?

I am using the following settings

```
data: function(rows, columns) {
            const result = [];
            for (let i = 0; i < rows; i++) {
              let row = [];
              for (let j = 0; j < columns; j++) {
                row.push('[' + i + ', ' + j + ']');
              }
              result.push(row);
            }
            return result;
          }(10, 10),
colHeaders: true,
minSpareRows: 2,
```

What should I change/add to replicate the issue?

**Comment by abrim** [comment]
Sorry I've been busy since I posted the bug & haven't been able to respond properly.  Here's a sample hotSettings that exhibits the problem:

```Javascript
hotSettings: {
          data: function(rows, columns) {
            const result = [];
            for (let i = 0; i < rows; i++) {
              let row = [];
              for (let j = 0; j < columns; j++) {
                row.push('[' + i + ', ' + j + ']');
              }
              result.push(row);
            }
            return result;
          }(10, 10),
          colHeaders: true,
          columns: [
            // this column is causing an infinite loop in vue
            { data: function(row) { return '*' }}
          ].concat(function(columns) {
            const result = []
            for (let i = 0; i < columns; i++) {
              result.push({ data: i })
            }
            return result
          }(10)),
          minSpareRows: 1
        }
```
without the calculated column or setting minSpareRows to 0, the code runs without issue.

Interestingly, if I pass a data prop to the element as so:

```html
<HotTable :root="root" :settings="hotSettings" :data="buildData(10,10)"></HotTable>
```

(where buldData is the function specified in the hotSettings data property) I get only twice the number of minSpareRows (i.e. 2 if minSpareRows=1) & no errors.

**Comment by AMBudnik** [comment]
Thank you for sharing the code. I have replicated the same error on my local machine. And I can also confirm that `minSpareRows` causes the issue.

**Comment by mrpiotr-dev** [comment]
Hi @abrim,
unfortunately, this issue is related to #50.
Moreover, in the vanilla version of Handsontable this is also working unstable: http://jsfiddle.net/6t0r0xx6/

**Comment by AMBudnik** [comment]
Please track progress to https://github.com/handsontable/vue-handsontable-official/issues/50
We close tickets that are duplicates.
