### ISSUE TITLE
removeRow not change data

### ISSUE THREAD

**Issue by superpig** [handsontable/vue-handsontable-official#39]
when i remove a row and afterRemoveRow event is fired, there is no influence on data, but the display of hansontable is changed.

**Comment by AMBudnik** [comment]
Hi @superpig 

I am using the simple code to check it

```
afterRemoveRow: function(i, amount){
    console.log(i, amount)
},
```

and it works fine on my local machine using the demo from this repository. Can you share your hook logic?

**Comment by cywcd** [comment]
Hello, is there any solution to this problem?

**Comment by AMBudnik** [comment]
Hi @cywcd 

I have checked the code on my local machine and it works well. Can you share your settings?

**Comment by cywcd** [comment]
Hi @AMBudnik 
I've set 'afterRemoveRow' but it's not effective to call an external call inside this function and the 'this' method has been defined. What's the reason?

**Comment by cywcd** [comment]
Hi @AMBudnik  
This is my local code.
`
const that = this;
afterRemoveRow: function(i, amount){
                        var vAslist = localStorage.getItem(“vAslist”);
                        vAslist = JSON.parse(vAslist);
                        var codeArr = [];
                        for(var j = 0; j < amount; j++){
                            if(vAslist[i] && vAslist[i].code){
                                codeArr.push(vAslist[i].code);
                                i++;
                            }
                        }

                        console.log(i, amount,codeArr)
                        if(codeArr.length > 0){
                            axios
                                .get(
                                    "/jeecg/mountain/link/mountainSession.do?deleteTopic",
                                    {
                                        params: {
                                            account: localStorage.getItem(“executionAdmin_account”),
                                            codeList:codeArr.toString()
                                        }
                                    }
                                )
                                .then(res => {
                                    that.loading = false;
                                    if (res.data.success) {
                                        that.$Message.success(res.data.msg);
                                        that.searchFn(that.searchVo);
                                    } else {
                                        that.$Modal.info({
                                            title: "提示：",
                                            content: res.data.msg
                                        });
                                    }
                                })
                                .catch(error => {
                                    that.loading = false;
                                });
                        }

                    },`

**Comment by AMBudnik** [comment]
Hi @cywcd 

can you record a demo to let me see how it works on your end?

**Comment by AMBudnik** [comment]
I believe that we can close the issue as there are no news since May
