### ISSUE TITLE
Why I cannnot install handsontable-official? urgent!

### ISSUE THREAD

**Issue by simon9124** [handsontable/vue-handsontable-official#41]
Thanks for the development team for develop the handy component, but I encountered some problem in my vue-cli project when installing vue-handsontable-official:

The first is about installing handsontable-official that it reply "peerDependencies WARNING vue-handsontable-official@^1.1.0 requires a peer of handsontable@^0.35.1 but handsontable@0.36.0 was installed!".

**But handsontable now is handsontable@^0.36.**

And then I try to install for "npm install handsontable" and "npm install vue-handsontable-official", it replay me another 2 wranings: 

**1."Couldn't find preset "es2015" relative to directory "C:\\Users\\shaohong\\Desktop\\vue\\smart-ui\\node_modules\\_vue-handsontable-official@1.1.0@vue-handsontable-official"'
2."Failed to find '~handsontable/dist/handsontable.full.css'"**

Is there any problem with my method? In what order can I install handsontable-official? I really need to use such a convenient component!

**Comment by aalsiuser** [comment]
First i will talk about your 1st warning actually it is a dependency related issue, vue -handsontable needs "Babel-preset-es2015" plugin to work with vue.
And coming to 2nd warning it says it didn't find handsontable.css file in your node modules folder,so for this you need to install handsontable plugin .

**Comment by AMBudnik** [comment]
Thank you for your feedback @aalsiuser 
Let us know if you have managed to install the app.

**Comment by aalsiuser** [comment]
@AMBudnik Yes, i managed to install the app by following below steps
1.first i installed the official handsontable plugin for vue which is "vue-handsontable-official" and then compile through webpack.
2.when you compile you will get an error like this  **"Couldn't find preset "es2015" relative to directory "** for this you need to install plugin "Babel-preset-es2015" as a dependencyand then once again compile through webpack.
3.after compiling you will get an error saying that **"Failed to find '~handsontable/dist/handsontable.full.css'"** for this actually i don't know correct solution but what i understood is it that it cannot find  handsontable.full.css file in node modules so what i have done is to just delete **~** this symbol in nodemodules folder of vue-handsontable official and then it worked like a charm.
4.At last don't forget to install handsontable plugin in your project and import it in you vue file.

**Comment by AMBudnik** [comment]
Thank you for an update @aalsiuser 
And you @simon9124? 
We will be updating the wrapper in Q2 so all the feedback is highly appreciated

**Comment by simon9124** [comment]
@aalsiuser Thanks a lot! Sorry be late for studying "vue-croppa" these 2 days, I donnot know alot about  "Babel" and I will try your methods. For the Q2 I even throw the whole the file of address into the required index but still do not work, So let's expect the updating wrapper!

**Comment by simon9124** [comment]
@AMBudnik Year I will try to use "Babel" and expect the updating wrapper!

**Comment by simon9124** [comment]
@aalsiuser Could you help me how to operate to "delete handsontable.full.css" about Q2?

**Comment by simon9124** [comment]
@aalsiuser According to the  error prompt, I new a index "~handsontable/dist/" in "node_modules\_vue-handsontable-official@1.1.0@vue-handsontable-official\src" and throw "handsontable.full.css" in it, luckly no error this time! Is the method the same to yours?

**Comment by aalsiuser** [comment]
@simon9124 Yeah!!!! your logic is equivalent to mine but i have done in another way like bringing whole  vue-handsonable folder from the node-modules folder to project directory and then throwing handsontable.full.css????**And you have doubt why i did it ????**Yes!! there is a reason behind it actually my node-modules folder is ignored by git while pushing code to remote so for this reason i have done the above way.

**Comment by simon9124** [comment]
@aalsiuser AHAHAHA~It makes me remember the sentence "Great minds think alike"! ^_^

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same problem in v2.0.0-beta1+
