### ISSUE TITLE
afterChange event calling twice? Urgent

### ISSUE THREAD

**Issue by aalsiuser** [handsontable/vue-handsontable-official#44]
when editing a cell after change event is called twice and validation is overrided.
So kindly please help anyone from the community.

**Comment by AMBudnik** [comment]
Hi @aalsiuser 

for each change, the `afterChange` hook is called once. It only runs twice after table initialization.
Can you share your code? It looks like there is some operation that calls it independently.

**Comment by mrpiotr-dev** [comment]
Hi @aalsiuser,
this issue is related to #50. There you can follow the work progress.
