### ISSUE TITLE
Cells restored when other Cells changed

### ISSUE THREAD

**Issue by soakit** [handsontable/vue-handsontable-official#45]
![gif](https://user-images.githubusercontent.com/11240668/37515353-8150c4b6-2945-11e8-8fbb-8dbbace9703e.gif)

but there is no problem while not using **vue version**
https://jsfiddle.net/105e9ope/89/

**Comment by AMBudnik** [comment]
Hi @soakit 

it works fine in the demo that you've sent. Can you share a demo where the issue is replicable? Does it use the latest version of Handsontable?

**Comment by soakit** [comment]
In your repository **vue-handsonetable-official**,
replace  **hotSettings** in the file **/demo/src/sampleApp.vue** with the hotSettings of the link https://jsfiddle.net/105e9ope/92/ , that can reproduce the issue

**Comment by AMBudnik** [comment]
Thank you. I have replicated the issue. The demo uses version v0.35.1 of Handsontable on my local machine (which is hardcoded).
Can you try to load the version 0.38.1 by npm and check if the issue is still there?

**Comment by soakit** [comment]
I have tried 0.38.1, it has been resolved. Thank you!

**Comment by AMBudnik** [comment]
Great! Thank you for confirmation @soakit
