### ISSUE TITLE
Handsontable.Dom undefined with vue handsontable

### ISSUE THREAD

**Issue by MatthiasRMS** [handsontable/vue-handsontable-official#5]
I'm using Handsontable Vue integration, and I'd like to use a custom renderer.
In your examples, you have: 

```
function imageRenderer (instance, td, row, col, prop, value, cellProperties) {
    var escaped = Handsontable.helper.stringify(value),
      img;

    if (escaped.indexOf('http') === 0) {
      img = document.createElement('IMG');
      img.src = value;

      Handsontable.Dom.addEvent(img, 'mousedown', function (e){
        e.preventDefault(); // prevent selection quirk
      });

      Handsontable.Dom.empty(td);
      td.appendChild(img);
    }
    else {
      // render as text
      Handsontable.renderers.TextRenderer.apply(this, arguments);
    }

    return td;
  }

```

However `Handsontable.Dom` is undefined and the `addEvent` function fails.
Did you ever run in an issue like this ?

**Comment by jansiegel** [comment]
@MatthiasRMS, did you import Handsontable in a file where you're declaring the custom renderer?

```
import Handsontable from 'handsontable';
```

**Comment by mouradmamassi** [comment]
Hello the probleme is that **Handsontable.Dom** doas not defined but the **Handsontable.dom** is defined so you must juste write "**Dom**" in lower case

**Comment by claudiozoocial** [comment]
@mouradmamassi thanks!!! it works!

**Comment by iftu06** [comment]
i face a similar problem in handsontable angular wrapper. i used following line
           Handsontable.dom.empty(td);

it shows an error like 
 TypeError: Cannot read property 'dom' of undefined

I imported  handsontable.
