### ISSUE TITLE
Validation does not work when using objects

### ISSUE THREAD

**Issue by dshinton-qstart** [handsontable/vue-handsontable-official#50]
Validation works when data is formatted as an array of arrays, but does not work when using an array of objects with a column definitions that use the `data` property.

See https://codepen.io/anon/pen/ZxVMqE?editors=0010 for an example.

PS: This issue was created based on a conversation found in Issue #35. Please see those comments for additional details.

**Comment by gurvancampion** [comment]
Having the same issue, it seems the validation is working as when you get the cell meta the property "valid" is set to false. 
Then if you edit again the cell, it will be displayed in red.

https://codepen.io/anon/pen/GxzKVb?editors=0010

**Comment by mrpiotr-dev** [comment]
Hi @dshinton-qstart.
This bug occurs because of observing data changes.
Vuejs observes changes in objects but doesn't do it in arrays.
I think this is a high priority.

**Comment by aalsiuser** [comment]
Hi,

Can i know when this Bug is gonna be resolved?
I have an urgent need to do Handsontable table validation through array of objects........Thank you in advance.

**Comment by AMBudnik** [comment]
Hi @aalsiuser this issue is a part of an Epic issue https://github.com/handsontable/vue-handsontable-official/issues/64 planned for September. I hope that we will be able o fix them all but I can't make any promises.

**Comment by jansiegel** [comment]
Developed in #74

**Comment by DoubleCorner** [comment]
Is this bug has been solved ?

**Comment by AMBudnik** [comment]
Hi @Rainy-Bear, yes, this issue should be gone after updating to @handsontable/vue 3.0.0 or newer.

**Comment by muei** [comment]
```
"@handsontable/vue": "^4.1.1",
"handsontable": "^7.4.2",
```
Also has this problem.

**Comment by AMBudnik** [comment]
Hi @muei 

Thank you for reporting. Do you use the same approach as the Author? If not please share an example where the issue can be replicable.
