### ISSUE TITLE
vue-handsontable-official

### ISSUE THREAD

**Issue by inputherf** [handsontable/vue-handsontable-official#51]
When using VUE version, it is not possible to use the normal version of the function, may I ask when the framework version of the document will be issued？
Now I need to merge the cells of the header, but the vue version does not work.please hellp me
![kq6f m72us2_ sd nci6](https://user-images.githubusercontent.com/28945810/40759050-e62f5c40-64c2-11e8-947d-c7ca22b72ea9.png)
![t4n8 d3g9e_2c 8vo p a](https://user-images.githubusercontent.com/28945810/40759051-e66167f8-64c2-11e8-9309-be52ed839dbb.png)

**Comment by AMBudnik** [comment]
Hi @inputherf 

`rowspan` is yet unavailable option for the `nestedHeaders`.
