### ISSUE TITLE
How to registry a custom renderer

### ISSUE THREAD

**Issue by chenghsuan** [handsontable/vue-handsontable-official#52]
Hi there~
I have a problem that how to registry the custom renderer with HotTable?
If use HandsonTable.js can use following to deal with 
`Handsontable.renderers.registerRenderer('asterix', asterixDecoratorRenderer);`

Is there any way to handle custom renderer?

**Comment by AMBudnik** [comment]
Hi 

here's https://github.com/handsontable/vue-handsontable-official/issues/27 a topic with demos for custom renderers

**Comment by mrpiotr-dev** [comment]
Duplicate of #27
