### ISSUE TITLE
The width setting of the vue-handsontable plug-in does not work

### ISSUE THREAD

**Issue by inputherf** [handsontable/vue-handsontable-official#54]
I'm sorry to bother you again. I just started this plug-in. I have encountered many problems when using it recently, but the Vue-handsontable document is too simple to understand.This time I want to set the width of the table, and if the content of the table exceeds the width of the current screen let the table overflow:auto;But the parent box is overflow:hidden.I hope so, but now setting the width doesn't work and the table is scrolling with the entire page!Eager to find a solution.Thank you very much!

![1529398876](https://user-images.githubusercontent.com/28945810/41587720-6efd418a-73e2-11e8-8866-ff9d243da4a5.png)

**Comment by AMBudnik** [comment]
Hi @inputherf 

can you share your example in a Stackblitz od JSFiddle?

**Comment by inputherf** [comment]
@AMBudnik thanks , I have solved the problem.(#^.^#)

**Comment by AMBudnik** [comment]
Great! Thanks for an update
