### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Taxman972** [handsontable/vue-handsontable-official#55]
I can't install hansonTable for now even with the installation [guide](https://github.com/handsontable/vue-handsontable-official/wiki/Installation-with-Handsontable-CE).

So I have few question :

* Shouldn't vue be loaded first ?
* Why there is no `Vue.use` command ?

Maybe like this :
<pre>
import Vue from 'vue';
import HotTable from '@handsontable/vue';
Vue.use(HotTable);
</pre>

**Comment by AMBudnik** [comment]
You can use CLI and create an app automatically (check the command on the bottom of https://cli.vuejs.org/) and then proceed with the steps that are written in our Guide. 
After you create an app using the command `create`

you should get something like this

![image](https://user-images.githubusercontent.com/10757813/41712918-0d124dba-754c-11e8-8dd1-634f2dea79e6.png)

**Comment by Taxman972** [comment]
I'm trying to use HandsonTable inside an application created with Laravel/vueJS all others plugins used so far are working with 
<pre>
import YourPlugin from 'path/your-plugin';
Vue.use(YourPlugin);
</pre>
And inside the Laravel view I can use the plugin
<pre>
<\your-plugin><\/your-plugin\>
</pre>

Why this plugin is different ? And how to use it in this configuration ?

**Comment by AMBudnik** [comment]
Hm... I see. I thought that you're just starting a project. We'd need to check that. Maybe we're missing some settings in the wrapper.

**Comment by wojciechczerniak** [comment]
Handsontable for Vue is not a plugin. It's a component.

The Vue.js documentation is very specific when `Vue.use()` should be used and Handsontable for Vue doesn't do a single thing from [that list](https://vuejs.org/v2/guide/plugins.html).

To use component in Vue you need to import and register it within component that will use it. Just like the Vue docs say: https://vuejs.org/v2/guide/components-registration.html#Local-Registration Or register it globally if you prefer.

Your examples don't mention component registration:

    components: {
       HotTable
    }

Can you show us the rest of your code?

**Comment by Taxman972** [comment]
More code as asked:

**1st try - using it in the view | Console error : ReferenceError: HotTable is not defined on line 263**

*main.blade.php*
<pre>
&lt;div id="main"&gt;
...
    &lt;div id="hot-preview"&gt;
        &lt;HotTable :settings="hotSettings"&gt;&lt;/HotTable&gt;
    &lt;/div&gt;
...
&lt;/div&gt;
<script>
const vm = new Vue({
    el: '#main',
    components: {
        HotTable // Line 263
    },
    data: {
        ...
        hotSettings: {
            data: [['sample', 'data']],
            colHeaders: true
        },
        ...
    }
});
</script>
</pre>

**2nd try in the component | Console error : ReferenceError: HotTable is not defined on line 536**
<pre>
*pannelComponent.vue*
&lt;template&gt;
    &lt;div label="Data Grid" name="data"&gt;
    ...
        &lt;div id="hot-preview"&gt;
            &lt;HotTable :settings="hotSettings"&gt;&lt;/HotTable&gt;
        &lt;/div&gt;
    ...
    &lt;/div&gt;
&lt;/template&gt;
&lt;script&gt;
    export default {
        data() {
            return {
                ...
                hotSettings: {
                    data: [['sample', 'data']],
                    colHeaders: true
                }
            }
        },
        components: {
            HotTable // Line 536
        },
    }
&lt;/script&gt;
</pre>

**Comment by wojciechczerniak** [comment]
You're missing the `import`, that's why HotTable is not defined.
```vue
<template>
    <HotTable :settings="{ ... }"></HotTable>
</template>

<script>
  import HotTable from '@handsontable/vue';

  export default {
    components: {
      HotTable
    }
  }
</script>
```

**Comment by Taxman972** [comment]
I finally found the problem, it's impossible to import camelCase component. That strange but at least this code works : 

<pre>
&lt;script&gt;
    import handsontable from '@handsontable/vue';
    export default {
        data() {
            return {
                ...
                hotSettings: {
                    data: [['sample', 'data']],
                    colHeaders: true
                }
            }
        },
        components: {
            handsontable
        },
    }
&lt;/script&gt;
</pre>
