### ISSUE TITLE
vue-cli2.9.3打包报错  模块内部找不到自己的依赖 '~handsontable/dist/handsontable.full.css‘

### ISSUE THREAD

**Issue by qq986063761** [handsontable/vue-handsontable-official#57]
在2.9.3脚手架下，通过 npm install vue-handsontable-official 安装的1.0.0 版本打包编译时，报错

in ./node_modules/_vue-handsontable-official@1.0.0@vue-handsontable-official/src/HotTable.vue
Module build failed: Error: Failed to find '~handsontable/dist/handsontable.full.css'

可能因为打包配置问题，这个问题我可以通过什么办法修改打包配置解决呢？是不是vue-cli某个依赖模块版本出了问题；

**Comment by jansiegel** [comment]
@qq986063761 Have you tried using `@handsontable/vue` instead of `vue-handsontable-official`?
The `vue-handsontable-official` package is now outdated, and will soon be labeled as deprecated.

**Comment by inputherf** [comment]
这个简单，就是这个文件自己的问题，它默认找的依赖的地址有问题。
![image](https://user-images.githubusercontent.com/28945810/41769457-e7354b78-7641-11e8-9216-9e269f440962.png)
最后提醒一下，如果部署到服务器的时候，还要在服务器改地址链接！

**Comment by jansiegel** [comment]
If I understand correctly, there's a problem with the `.css` file location, which should no longer be a problem in the new version (`@handsontable/vue`), as the `css` files are no longer a part of the package, which means you'll need to import them separately.
