### ISSUE TITLE
contextMenu callback not fire

### ISSUE THREAD

**Issue by superpig** [handsontable/vue-handsontable-official#63]
here is `contextMenu` config, when i click the menu item, whick does not trigger the callback
```js
contextMenu: {
    callback: function (key, selection, clickEvent) {
        console.log(clickEvent);
    },
    items: {
        row_above: {
            disabled: function () {
                return this.getSelectedLast()[0] === 0;
            }
        }
    }
}
```

**Comment by AMBudnik** [comment]
Hi @superpig 

try this

```
contextMenu: {
                items: {
                  "make_sample": {
                        name: "sample",
                        callback: function(key, options) {
                        console.log('sample')
                        },
                      },
                }
              },
```

you need to define an `items` object.

**Comment by superpig** [comment]
@AMBudnik it does not work for me,  my version is "vue-handsontable-official": "^1.1.0" and  "handsontable": "^0.35.1"

**Comment by wojciechczerniak** [comment]
@superpig Please check if you have same issue with the latest versions of Handsontable and Vue wrapper. This issue could have been already solved.

**Comment by Even-Lau** [comment]
"handsontable": "^7.0.2", applied to my vuejs application. Can not work too.

**Comment by Even-Lau** [comment]
I just figured out that it is a css trick. The value of z-index is not big enough. 
`.htContextMenu:not(.htGhostTable) {
    display: none;
    position: absolute;
    z-index: 1060;
}`
