### ISSUE TITLE
Make a workaround for the `cssstyle` package.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/vue-handsontable-official#65]
Currently, one of the `devDependencies` is my fork of the `cssstyle` package. (More information here: https://github.com/jsakas/CSSStyleDeclaration/issues/63).
This is not an optimal solution, plus it breaks `npm audit`, as it's not published to npm.

The new approach overwrites the `Number` prototype by adding `toLowerCase` and `split` methods for the tests, as they break on them specifically.

**Comment by wojciechczerniak** [comment]
Fix for CSSStyleDeclaration in https://github.com/jsakas/CSSStyleDeclaration/pull/52 was merged and released as 1.0.0: https://github.com/jsakas/CSSStyleDeclaration/releases/tag/v1.0.0 

@jansiegel Maybe we should revert this workaround? :broken_heart:
