### ISSUE TITLE
wordWrap: false not working

### ISSUE THREAD

**Issue by k3341095** [handsontable/vue-handsontable-official#67]
columns: [
                    {title: 'address', data: 'raddress', wordWrap: false},
]
The nowrap feature does not seem to work.
But

                autoWrapCol: true,
                autoWrapRow: true,
                currentRowClassName: 'currentRow',
                wordWrap: false,

The main option works well.

vue-handsontable : 2.0
handsontable: 5.0

I'm sorry I'm not good at English.

**Comment by AMBudnik** [comment]
Hi @k3341095 

I've tested it on this example https://codepen.io/anon/pen/KBvXVy and it seems to work fine on Chrome. If you change the `wordWrap` to `false` it shows the whole cell content and makes the second line.
