### ISSUE TITLE
documentation for database query in Vue

### ISSUE THREAD

**Issue by gbih** [handsontable/vue-handsontable-official#69]
I've poured over the handsontable documentation, for both community and pro versions, searching for  examples of how to fetch data from a database in Vue. Unfortunately, there is very little information out there. Can you point out any online examples, if they exist?

The ideal would be Vue + Axios.

**Comment by AMBudnik** [comment]
Hi @gbih 

not sure if you'll find this one helpful https://docs.handsontable.com/pro/5.0.0/tutorial-load-and-save.html but it's an only example for database connection that we have
