### ISSUE TITLE
How can I get the data

### ISSUE THREAD

**Issue by bd8** [handsontable/vue-handsontable-official#7]
Hi,

i know its not a issue but I can´t get the current data and send it with axios for example.

It is possible to get a basic code for that? Thanks

**Comment by eard7** [comment]
Maybe a little too late but hope this help someone in the future,

You need to put a ref to your hot-table component
`<hot-table root="testHot" ref="testHot" :settings="handsonSettings"></hot-table>`

and then call this function
`this.$refs.testHot.table.getData()`

It's important to say that "table" is the instance returned by the handsontable constructor, so you can call all the handsontable methods using the "table" prop of the hot-table instance.

**Comment by TJKoury** [comment]
@eard7 I tried that but am getting "TypeError: Cannot read property 'getData' of undefined".

I've analyzed the component in Vue Tools (and dumped it to console), the Vue instance does not contain the property 'table'.

Any ideas?

**Comment by eard7** [comment]
@TJKoury That's weird. The code i published is what worked for me. Did you installed the handsontable dependency? (npm install -s handsontable)
EDIT.
Forget that, vue-handsontable-official should install it automatically.
I can't figure out another reason, but what is for sure is that the handsontable instance is not being initialized :/.
If you go to vue-handsontable-official/src/helpers.js, the hotInit function is where the Handsontable instance is created.

**Comment by TJKoury** [comment]
Found the problem.  The instance can only be accessed after it has been initialized!

**Comment by TJKoury** [comment]
I had to add a property to the parent Vue instance (this.mounted) when it's mounted, and check for that property whenever I want to save data.

Also, trying to use this with Vuex two-way binding is very difficult.

**Comment by eard7** [comment]
@TJKoury i see, i didn't had that problem because i accessed the instance with the click of a button (some time after the component mounted). Glad it worked for you, and yeah it's a little tricky but works.

**Comment by TJKoury** [comment]
@eard7 Thanks.  Also if anyone else is having issues with Vuex, try listening for afterChange events on the table and feeding data back to mutations:

```
....
afterChange: (changes, source) => {
          if (this.mounted && source === 'edit') {
          this.$store.commit('ontology', this.getTableData())
     }
},
methods: {
    getTableData: function () {
        return this.$refs.oHOT.table.getData()
    }
...... }
```

**Comment by aspben** [comment]
@TJKoury  Can you expand you code a little bit before the afterchange: 

if i try your suggestion like this : 
```
data: function () {
    return {
      root: 'testHot',
      vueData: [[1, 2, 3, 4]],
      hotSettings: {
        minSpareRows: 1,
        rowHeaders: true,
        colHeaders: [
          'player1',
          'player2',
          'seed',
          'club'
        ],
        afterChange: function (changes, source) {
          console.log(this.getData())
          console.log(this)
          if (this.mounted && source === 'edit') {
            this.$store.commit('SAVE_HANDSONTABLE_DATA', this.getData)
          }
        }
      }
    }
```

this refer to handsontable instance and i cannot access the store directly. this.$store = undefined

there is something i am missing here. Thank for your help

**Comment by PhilAndrew** [comment]
You said : @aspben this refer to handsontable instance and i cannot access the store directly. this.$store = undefined

I have the same problem. How to solve?

**Comment by aspben** [comment]
@PhilAndrew 
Finally i got it working like this : 

```
afterChange: function (changes, source) {
          console.log(source)
          if (source === 'edit') {
            this.rootElement.__vue__.$store.dispatch('updatePlayerList', this.getData())
          }
```

hope this work for you too !

**Comment by TJKoury** [comment]
@PhilAndrew @aspben I ended up not using $store directly.  I created a computed property and used a method to set the value.

**Comment by kieranongh** [comment]
If you use a bit of JavaScript and Vue magic, I just got this working for me
(Syntax is ES6)
```
data() {
   return {
     hotSettings: {
       ...
       afterChange: this.afterChangeVue
       ...
     }
   }
},
methods: {
    afterChangeVue(changes, source) {
      console.log('changes, source => ', changes, source);
      console.log('this.$store => ', this.$store);
    },
```

This lets you use the Vue instance `this`, but can no longer use the Handsontable instance `this`. I don't think I'll need it, so I'm happy to make that compromise

**Comment by francoismart** [comment]
Hello how do you access the HotTable component from Parent (in the case Handsontable is inside a HotTable.vue inside another main component) ?

**Comment by mrpiotr-dev** [comment]
I think we can close this issue. Feel free to reopen if you find the same problem.

@francoismart Could you create a new issue with details?
