### ISSUE TITLE
how to get the mergeCells data in v5.0.0

### ISSUE THREAD

**Issue by alisanguo** [handsontable/vue-handsontable-official#71]
how to get the mergeCells data in v5.0.0? it seems that mergedCellInfoCollection has been removed

**Comment by WGL878420** [comment]
同问  我想在要动态合并不是静态的要如何写？

**Comment by AMBudnik** [comment]
Hi @alisanguo @WGL878420 
we do not have any official API for that but you can use the `afterMergeCells` callback to get predefined and new merged areas of cells.
Here is an example http://jsfiddle.net/sczypvb4/

**Comment by alisanguo** [comment]
we can use "hotTable.getPlugin('mergeCells').mergedCellsCollection.mergeCells" to the mergeCells data
