### ISSUE TITLE
Unable to get source data in type: autocomplete

### ISSUE THREAD

**Issue by contrarianaupong** [handsontable/vue-handsontable-official#72]
In the settings, the  **source: this.getTestOption()**, got undefined. 
Is it possible to get the array in the local data / computed data?

settings: {
        columns: [
          {
            type: "autocomplete",
            source: this.getTestOption(),
            strict: true,
            allowInvalid: false
          },
          
        ],
}

**Comment by contrarianaupong** [comment]
Or I need to write a custom renderer for this case?

**Comment by rafaph** [comment]
I'm having the same issue, looks like custom renderer is the way.

**Comment by wojciechczerniak** [comment]
We can't help without an example. Can you create simple JSFiddle that replicates the issue?

**Comment by wojciechczerniak** [comment]
Please reopen with an example. You can use this JSFiddle as a starting point: https://jsfiddle.net/handsoncode/4owqzasd/

**Comment by carlospas** [comment]
I don't know how or I can't getSourceData(), afterChange  I'm using vue.
what can I do? you could help me, please?

https://jsfiddle.net/yfjdubvo/

**Comment by hansfelix** [comment]
> I don't know how or I can't getSourceData(), afterChange I'm using vue.
> what can I do? you could help me, please?
> 
> https://jsfiddle.net/yfjdubvo/

Check this fiddle @carlospas 
https://jsfiddle.net/hansfelix50/ev509wu6/

**Comment by AMBudnik** [comment]
Thank you for your feedback @Hansfelix50 
@carlospas I've also answered the same question here https://github.com/handsontable/vue-handsontable-official/issues/175
