### ISSUE TITLE
Suggestion: Vue specific documentation on how to access plugins etc

### ISSUE THREAD

**Issue by zxc23** [handsontable/vue-handsontable-official#75]
I had a bit of a hard time accessing plugins because the existing documentation was all for React, as far as I could tell. I eventually got it to work like this:

```
let hot = this.$refs.hot.table
let search = hot.getPlugin('search')
```

and so on, from within the component, with ref="hot" in the hot-table element attributes.

**Comment by jansiegel** [comment]
@zxc23 We just released `@handsontable/vue` `3.0.0` and updated the documentation.
It now contains an example on how to reference the Handsontable instance: https://docs.handsontable.com/pro/5.0.2/frameworks-wrapper-for-vue-hot-reference.html
