### ISSUE TITLE
Add more examples to the documentation

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/vue-handsontable-official#81]
We should improve our documentation by adding most requested examples:

- [x] Custom Context Menu
- [x] Custom Editor #73 
- [x] Custom Renderer #27 
- [x] Accessing Handsontable instance #75

**Comment by jansiegel** [comment]
All of these are now online at:
* http://docs.handsontable.com/pro/vue
* http://docs.handsontable.com/vue
