### ISSUE TITLE
How can I get the ht instance in 3.0

### ISSUE THREAD

**Issue by johnson4932** [handsontable/vue-handsontable-official#83]
Hello

In 2.0, I need to put a `ref` to my hot-table component, and use `this.$refs.myTable.table` to get ht instance. ref: https://codepen.io/swistach/pen/NMzmPa
```html
<div id="test-hot-app">
  <button v-on:click="changeData">changeData()</button>
  <hot-table :root="root" :settings="hotSettings" ref="myTable"></hot-table>
</div>
```
```javascript
new Vue({
  el: "#test-hot-app",
  data: function() {
    return {
      root: 'testHot',
      hotSettings: {
        data: Handsontable.helper.createSpreadsheetData(10, 10),
        rowHeaders: true,
        colHeaders: true,
      }
    }
  },
  methods: {
    changeData: function() {
      this.hotSettings.data[0][1] = 'Ford';
      this.$refs.myTable.table.render();
    }
  },
  components: {
    HotTable
  }
});
```

In 3.0 , `this.$refs.myTable.table` is undefined. I use `$refs.myTable._data.hotInstance` to get instance now.

is it correct ?

Thanks !

**Comment by jansiegel** [comment]
@johnson4932 In `3.0.0` the `table` property holding the reference to the Handsontable instance was renamed to `hotInstance`, so the proper way to address it in your case should be `this.$refs.myTable.hotInstance`. https://codepen.io/js-ziggle/pen/mzPGbW

Somehow it slipped through the cracks and never got mentioned in the release notes, thanks for pointing that out!
