### ISSUE TITLE
handsontable 3.0 Performance issue

### ISSUE THREAD

**Issue by k3341095** [handsontable/vue-handsontable-official#85]
### Steps to reproduce

1. nuxt.js + handsontable 3.0 + chrome 69
2. 700 records view
3. ctrl + a
  show chrome console : 
[Violation] 'keydown' handler took 541ms
[Violation] Forced reflow while executing JavaScript took 479ms
4. scroll wheel down
[Violation] 'scroll' handler took 849ms
[Violation] Forced reflow while executing JavaScript took 762ms
[Violation] 'scroll' handler took 954ms
[Violation] Forced reflow while executing JavaScript took 777ms
[Violation] Handling of 'wheel' input event was delayed for 556 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.
C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:2160 [Violation] 'scroll' handler took 756ms

error code node_modules\handsontable\dist\handsontable.js:2160

and I made a checkbox.
row is 700

check all -> 
testdata.map((v) => {
v.checked = true
}

You have to wait 2 seconds.

It only takes 2ms to execute the loop.
            console.time('ttt')

            let selectRows = this.$refs.assignTable.hotInstance.getSelected()
            for (var i = selectRows[0][0]; i <= selectRows[0][2]; i++) {
                this.filteredAssignLists[i].checked = !this.filteredAssignLists[i].checked
            }
            console.timeEnd('ttt')

console.log --> ttt: 1 or 2 ms

Is there a quick fix?

another test 
I may be involved in rendering 
add renderAllRows: true,

same 700 row  8 column 
render time Slightly slow

ctrl + a & checked true

[Violation] 'mousedown' handler took 1323ms
[Violation] Forced reflow while executing JavaScript took 1146ms
[Violation] Forced reflow while executing JavaScript took 35ms
4C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:2172 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
addEventListener @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:2172
registerListeners @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:20075
updateMainScrollableElements @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:20296
Core.updateSettings @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:11961
updateHotSettings @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\@handsontable\vue\dist\vue-handsontable.js:180
handler @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\@handsontable\vue\dist\vue-handsontable.js:142
run @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\vue\dist\vue.runtime.esm.js:3229
flushSchedulerQueue @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\vue\dist\vue.runtime.esm.js:2977
(anonymous) @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\vue\dist\vue.runtime.esm.js:1833
flushCallbacks @ C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\vue\dist\vue.runtime.esm.js:1754
C:\Users\puresoft\Project\boomr2\boomr-iview\node_modules\vue\dist\vue.runtime.esm.js:1749 [Violation] 'message' handler took 5333ms
[Violation] Forced reflow while executing JavaScript took 4067ms

It takes more than 5 seconds ...

same data jquery version datatables -> check all -> 0.001 second

and handsontable jquery version -> check all -> 100ms

### Your environment
* Vue wrapper version: nuxt.js 1.42
* Handsontable version: 3.0
* Browser Name and version: chrome 69
* Operating System: windows 10

**Comment by k3341095** [comment]
I tried another test
error Project\boomr2\boomr-iview\node_modules\handsontable\dist\handsontable.js:2172 
      if (window.addEventListener) {
        element.addEventListener(eventName, callbackProxy, false);   -> 2172
      } else {
        element.attachEvent('on' + eventName, callbackProxy);
      }

2172 break point

I manually changed the data value.
$vm.responseData.assign[4].checked = true

Chrome will raise an error.
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

2172 eventName 
mouseup -> mousemove -> mouseup -> mousemove -> mousemove -> mouseup -> wheel -> wheel
-> wheel -> wheel -> scroll -> visibilitychange -> keyup -> keydown

It changes in order.
Is this a normal operation?
I did not move or click the mouse or scroll the wheel.
 
This part does not seem to be related to speed. ㅜㅜ

**Comment by AMBudnik** [comment]
Hi @k3341095 

what are the settings for Handsontable? Do you use `setDataAtCell` or `updateSettings` during any tested process?

**Comment by k3341095** [comment]
settings: {
                colHeaders: true,
                rowHeaders: true,
                columnSorting: true,
                manualColumnMove: true,
                manualColumnResize: true,
                autoWrapCol: false,
                autoWrapRow: false,
                sortIndicator: true,
                outsideClickDeselects: false,
                currentRowClassName: 'htCurrentRow',
                viewportRowRenderingOffset: 10,
                // renderAllRows: true,
                wordWrap: false,
                columns: [
                    {type:'checkbox', data: "checked", className: 'htCenter'},
                    {title: '주문번호', data: 'od_no'},
                    {title: '수취인', data: 'r_name'},
                    {title: '주소', data: 'r_address', wordWrap: false},
                    {title: '제품명', data: 'p_name'},
                    {title: '옵션', data: 'p_option'},
                    {title: '수', data: 'p_qty', className: 'htCenter'},
                    {title: '배', data: 'p_bqty', className: 'htCenter'},
                    {title: '희망배송일', data: 'dt_hope'},
                    // {title: '판매처', data: 'shop.name'},
                    // {title: '제조사', data: 'fac'},
                    // {title: '수취인 전화1', data: 'rtel1'},
                    // {title: '수취인 전화2', data: 'rtel2'},
                    // {title: '우편번호', data: 'rzipcode'},
                    // {title: '구매자', data: 'cname'},
                    // {title: '구매자 전화1', data: 'ctel1'},
                    // {title: '구매자 전화2', data: 'ctel2'},
                    // {title: '배송메세지', data: 'dmessage'},
                    // {title: '선불', data: 'prepay'},
                    // {title: '착불', data: 'postpay'},
                    // {title: '판매쇼핑몰', data: 'sname'},
                    // {title: '쇼핑몰주문번호', data: 'sno'},
                    // {title: '주문상태', data: 'assign.csStatus', className: 'htCenter'},
                    // {title: '배송상태', data: 'assign.deliveryStatus', className: 'htCenter'},
                    // {title: '주문등록일', data: 'assign.date.assignDate'},
                    // {title: '입고대기일', data: 'assign.date.shippingWait'},
                    // {title: '입고완료일', data: 'assign.date.shipComplete'},
                    // {title: '출력완료일', data: 'assign.date.printComplete'},
                    // {title: '배송출발일', data: 'assign.date.deliveryStart'},
                    // {title: '배송완료일', data: 'assign.date.deliveryComplete'},
                    // {title: '지사출발일', data: 'assign.date.upTruck'},
                    // {title: '지사도착일', data: 'assign.date.downTruck'},
                ],
                afterOnCellMouseDown: (event, coords) => {
                    if (coords.col === -1 && coords.row >= 0) {
                        console.log('modal생성')
                        this.$modal.show(detailOrder,{
                                orderid: this.responseLists.data[coords.row].od_no,
                            },{
                                width: 1000,
                                height: 600,
                                draggable: true,
                        })
                    }
                },
                // colHeaders: this.colHeaderCheckbox,
                // afterChange: function () {
                //     debugger
                //     this.rootElement.__vue__.$emit('afterChange', this.getData())
                // },
                afterColumnSort: function () {
                    this.rootElement.__vue__.$emit('afterChange', this.getData())
                }
            },

only this setting... 
afterOnCellMouseDown and  afterColumnSort 
I deleted it.
But the same symptoms.

**Comment by AMBudnik** [comment]
The `renderAllRows: true,` forces the table to load on the initialization so it takes longer when the data loads but scrolling is faster. It works the same for [offset](https://docs.handsontable.com/pro/6.0.1/Options.html#viewportColumnRenderingOffset). You shouldn't need to call `renderAllRows` if you do not have any misaligning issues. The 800 rows and couple of column's should slow down if it is not bulked with custom hook/renderer logic. However the checkbox may have a huge impact on the performance. Here is a demo that can help for the checkbox toggle http://jsfiddle.net/8b35uhf4/ the demo has 10'000 rows and still a checkbox state changes in a split of second

**Comment by k3341095** [comment]
> The `renderAllRows: true,` forces the table to load on the initialization so it takes longer when the data loads but scrolling is faster. It works the same for [offset](https://docs.handsontable.com/pro/6.0.1/Options.html#viewportColumnRenderingOffset). You shouldn't need to call `renderAllRows` if you do not have any misaligning issues. The 800 rows and couple of column's should slow down if it is not bulked with custom hook/renderer logic. However the checkbox may have a huge impact on the performance. Here is a demo that can help for the checkbox toggle http://jsfiddle.net/8b35uhf4/ the demo has 10'000 rows and still a checkbox state changes in a split of second



There is nothing wrong with jqeury + handsontable that I made.

Only slow on handsontable / vue.

**Comment by k3341095** [comment]
I tried it again

It seems to be related to height.

If you do not set the height of the div,
Setting the height on the div is pretty fast.

**Comment by AMBudnik** [comment]
Thank you for checking that. When you set a height Handsontable knows how many rows it should print.
