### ISSUE TITLE
How can I access the top tags? custome renderer

### ISSUE THREAD

**Issue by k3341095** [handsontable/vue-handsontable-official#86]
### Steps to reproduce

1. custom render parentNode return null

{title: '배송상태', data: 'del_status', className: 'htCenter', readOnly: true, renderer: this.deliveryRender},

        deliveryRender (instance, td, row, col, prop, value, cellProperties) {
            Handsontable.renderers.TextRenderer.apply(this,arguments);

td
<td class=​"htCenter htDimmed htNoWrap">​주문등록​</td>​

td.parentNode => null return ...

my another project handsontable.js and jquery site
tr.parentNode => <tr> tag return ..

how should ..
TD tag to access the upper TR tag
Can I add a class?

my another site source 
$(td).parent("tr").addClass("deliveryNormal");

I need help.

**Comment by AMBudnik** [comment]
Hi @k3341095 

in [this simple renderer](https://jsfiddle.net/s1w7mvab/) I can the same element `td.parentNode` and I get `tr` element in return.

And here https://jsfiddle.net/tuyhwmo6/ I add a class to the `tr` element and log it to check if it has been added correctly.

ADDED:

Sorry, I haven't noticed that it should be a Vue version. In Vue we surely get a lot of `null` values, but we also get all the needed TD elements for all the headers. Here is an updated demo https://codepen.io/anon/pen/yRpNje?editors=0010

**Comment by k3341095** [comment]
> Hi @k3341095
> 
> in [this simple renderer](https://jsfiddle.net/s1w7mvab/) I can the same element `td.parentNode` and I get `tr` element in return.
> 
> And here https://jsfiddle.net/tuyhwmo6/ I add a class to the `tr` element and log it to check if it has been added correctly.
> 
> ADDED:
> 
> Sorry, I haven't noticed that it should be a Vue version. In Vue we surely get a lot of `null` values, but we also get all the needed TD elements for all the headers. Here is an updated demo https://codepen.io/anon/pen/yRpNje?editors=0010


I am using nuxt.js.
plugin import vue handsontable, ssr: false

vue file
import Handsontable from 'handsontable'

and handsontable column setting 
{title: '주문번호', data: 'od_no', readOnly: true, renderer:this.odNoRender},

and.. methods
        odNoRender (instance, td, row, col, prop, value, cellProperties) {
            Handsontable.renderers.TextRenderer.apply(this,arguments);
            if(this.responseLists.data){
                if(this.responseLists.data[row].od_cs === 1) {
                    td.style.background = '#f0dece';
                }
            }
            return td;
        },


background color change very well

        odNoRender (instance, td, row, col, prop, value, cellProperties) {
            Handsontable.renderers.TextRenderer.apply(this,arguments);

            debugger
            if(this.responseLists.data){
                if(this.responseLists.data[row].od_cs === 1) {
                    td.style.background = '#f0dece';
                }
            }
            return td;
        },


From the debugger .. After stopping ..
td.parentNode

Returns a null value.

Is it wrong in nuxt.js?

**Comment by k3341095** [comment]
And I tried again.
https://codepen.io/anon/pen/yRpNje?editors=0010

        renderer: function (instance, td, row, col, prop, value, cellProperties) {
             Handsontable.renderers.TextRenderer.apply (this, arguments);
             debugger
             var parent = td;
             //parent.parentNode.className = 'myRow';
             console.log (parent.parentNode);
           if (parent.parentNode! == null) {
               parent.parentNode.className = 'myClass';
             console.log (parent.parentNode.className)
           }
          
           },

I copied and pasted it into my source.

Turn on the debugger
td.parentNode
Returns null.

**Comment by k3341095** [comment]
Resolved.

I do not get it right from render.

Is the correct td value coming in?

             if (td.parentNode! == null) {
                 console.log (td.parentNode)
             }

I come out to do this ...
Thank you for your reply.

I would like to add a lot of examples for handsontalbe / vue.
It's too hard.

**Comment by AMBudnik** [comment]
Do you get all the `null` values? I am asking because I get a dozen `null` values but after them, I get proper `tr` elements.

**Comment by AMBudnik** [comment]
Oh OK. Thank you for an update.
