### ISSUE TITLE
wtHolder height How do you fix it?

### ISSUE THREAD

**Issue by k3341095** [handsontable/vue-handsontable-official#88]
### Steps to reproduce

1. one button ( data update button)
2. <h-table id="assign-table" ref="assignTable" :data="filteredAssignLists" :settings='settings' style="width:100%"></h-table>

handsontable not option height 
Every time the button is pressed, data is taken from axios.
data is reset each time it is pressed.
However ... wtHolder height continues to increase.
Each click increases wtHolder height.
data array size [10] or less. But still the height
Grow

What is the problem ...
How can I fix it?

I am using nuxtjs and I am using 3.0 / 6.0.

### Demo

https://jsfiddle.net/handsoncode/4owqzasd/

### Your environment
* Vue wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @k3341095 

can you fill the example? It does not have any buttons.
