### ISSUE TITLE
Fix up main/top level docs/examples

### ISSUE THREAD

**Issue by mismith** [handsontable/vue-handsontable-official#90]
### Description
The simple examples in the README and docs of this repo seem to be out of date?

### Steps to reproduce
1. Visit https://github.com/handsontable/vue-handsontable-official#getting-started
2. In the code snippet below, there are a few oddities, IMO:
- `import Vue from 'vue';` ... the `Vue` variable is never used
- in the styles, `#test-hot` is referenced, but it doesn't exist in this component definition
- in the template, the `<HotTable />` component itself is wrapped in a div, with an ID attribute. Are either the wrapper or it having an ID set strictly necessary? If not, maybe they should be removed for focus/clarity?

1. Visit https://handsontable.com/docs/6.1.1/frameworks-wrapper-for-vue-installation.html
2. In the "Basic Usage" code snippet, there are similar eccentricities, plus:
- imported variable `HotTable` is not used—this weird thing is instead: `'hottable': Handsontable.vue.HotTable`; when I run this locally, it doesn't seem to work... might this be related to the JSFiddle hack (e.g. as linked below)? Is that hack documented or explained anywhere in detail?

### Demo
https://jsfiddle.net/3wrmcy05/

### Your environment
* Vue wrapper version: 3.0.0
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 69.0.3497.100
* Operating System: macOS 10.14

**Comment by mismith** [comment]
Also, the installation guide is out of date now for v3.0.0:

- https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide
-  https://github.com/handsontable/vue-handsontable-official/issues/8

**Comment by mismith** [comment]
Also, is there some way I can show you a repro case using v3.0.0? I notice the existing JSFiddles/Codepens I've found reference rawgit URLs, but since build artifacts (namely `dist/`) aren't in the source tree anymore, how should I reference the transpiled/minified source files?

**Comment by wojciechczerniak** [comment]
Thanks for reporting this @mismith 

You can use jsdelivr to get current or older releases: https://www.jsdelivr.com/package/npm/@handsontable/vue
