### ISSUE TITLE
Use vue component in the header loses all the event handlers

### ISSUE THREAD

**Issue by Guobacai** [handsontable/vue-handsontable-official#91]
### Description

Instead of rendering simple text in the header, I want to render a vue component. It can be done by returning the vueInstance.$el.outerHTML to "colHeaders". However, all the event handlers defined on that component are lost.
I would expect all those events should be kept.

### Steps to reproduce

1. Click the button outside of the table. It updates itself with click counts.
2. Click the button inside of the header of table. It doesn't update. 

### Demo

https://jsfiddle.net/guobacai/jtu4r3pf/37/
Note: Please suggest the correct way if I am doing this in wrong way.

### Your environment
* Vue wrapper version: 2.0.0
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 69
* Operating System: Mac

**Comment by AMBudnik** [comment]
Hey @Guobacai 

unfortunately, we do not support using external component inside the Handsontable table yet.
