### ISSUE TITLE
Investigate why we get `undefined` from `getCell` method

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/vue-handsontable-official#95]
### Description

Investigate why we get `undefined` from `getCell` method. Should we fix Handsontable or the wrapper?

### Steps to reproduce

1. https://github.com/handsontable/handsontable/commit/b911bab7daa6d726bddba699fed82dc1b6a3b769

### Your environment
* Vue wrapper version: unknown
* Handsontable version: unknown
* Browser Name and version: unknown
* Operating System: unknown

**Comment by jansiegel** [comment]
This looks like an issue with Handsontable, not the wrapper.

I've opened an issue for this in the main repo: handsontable/handsontable#5608
